### ISSUE TITLE
plugin list missing all standard plugins - only showing dropins

### ISSUE THREAD

**Issue by chrisputnam9** [wp-cli/extension-command#101]
Issue: "plugin list" is not returning the full list - only showing dropins
 - plugin status exhibits the same issue
 - plugin install works as expected, including recognizing if a plugin is already installed when I try to install it
 - All other commands that I have run work as expected
 - WP CLI version: 1.5.1
 - WordPress version: 4.9.6

This is happening on at least two sites, but works fine on others, so I suspect it is caused by some environmental aspect, but I have checked everything I can think of - symlinks, php settings, WP_PLUGIN_DIR constant, removing non-critical wp-config lines.

--debug does not reveal anything abnormal

I also confirmed the issue happens for the same site on two servers, one of which works for other sites - thus, to my satisfaction, the issue must be in the site's specific files or database.

What else can I try, or how can I gather more information?

Thank you,
Chris

**Comment by chrisputnam9** [comment]
I believe I figured this out - I was able to show the list correctly when I included --user=<super-admin-user>
Or, more fully, for my purposes:
`wp plugin list --user=$(wp super-admin list | head -n 1)`

Bug, or expected behavior of permissions?  I'm happy with my solution either way, but I will leave this open for someone wiser to weigh in.

**Comment by schlessera** [comment]
@chrisputnam9 Do I understand correctly that you're encountering this problem on multisite installs only?

**Comment by chrisputnam9** [comment]
You are correct, both cases I've encountered were multisite. But, not all multisites that I've worked with exhibit the issue.

**Comment by danielbachhuber** [comment]
@chrisputnam9 Can you try using `--skip-plugins=<plugin>` to [debug whether there might be a plugin](https://make.wordpress.org/cli/handbook/identify-plugin-theme-conflict/) causing the issue?

**Comment by chrisputnam9** [comment]
--skip-plugins did the trick! I'll see if I can find some time to narrow down which plugin it is later, but this is perfect for now - thanks for the help!
