### ISSUE TITLE
wp plugin install not works with runuser

### ISSUE THREAD

**Issue by VitalyEvrica** [wp-cli/extension-command#104]
Hi. When I install plugin which is in wp directory in zip archive with `runuser -l  wpuser1 -c 'wp plugin install myplugin.zip  --path=/var/www/wpuser1/data/www/domain1.tk/' ` it writes 
Warning: Couldn't find 'myplugin.zip' in the WordPress.org plugin directory.
Error: No plugins installed.
Btw, commands like 'wp core download... ' works

**Comment by VitalyEvrica** [comment]
Solved
su  wpuser1 -c 'wp plugin install  myplugin.zip  --path=/var/www/wpuser1/data/www/domain1.tk/'

**Comment by schlessera** [comment]
Glad you got it solved. The main issue is that `runuser` will change your working directory, so a relative path like `myplugin.zip` will not work.

However, for your future reference, GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support

The easiest way to get support is to join us in the #cli channel on the [Make WordPress Slack Team](https://make.wordpress.org/chat/).
