### ISSUE TITLE
Differences between 'wp-admin/update-core.php' vs 'wp plugin update --all'

### ISSUE THREAD

**Issue by austinginder** [wp-cli/extension-command#106]
While attempting to trace down why `wp plugin update --all` is randomly missing some paid/premium  plugin updates I discovered that WP CLI will only update plugins found in site_transient_update_plugins whereas the admin page `wp-admin/update-core.php` seems to be more forgiving and will update all plugins. I'll list steps to repeat. Warning this will include paid plugins however this scenario applies broadly for a wider range of plugins not just my sample set.

**Reproduce steps**
- Install User Role Editor Pro v4.47.1 (old version)
- Install WooCommerce Subscriptions v2.3.1 (old version)
- Visit `wp-admin/update-core.php` will show both have updates however User Role Editor Pro never makes it into `site_transient_update_plugins` as shown by running `wp eval "var_dump( array_keys(  get_option('_site_transient_update_plugins')->response ) );"`.
- Running `wp plugin update --dry-run --all` will only update WooCommerce Subscriptions while `wp-admin/update-core.php` will successfully update both plugins.

Any ideas why the `wp-admin/update-core.php` is able to update all plugins even buggy ones which never make it into the `site_transient_update_plugins`? Maybe there is someway to trick wp cli to include these rogue plugins?

**Comment by austinginder** [comment]
Digging in deeper, it appears that on the `update-core.php` the `$plugins = get_plugin_updates();` consistently outputs the 2 plugins however within `wp shell` that only outputs 1 plugin. With the User Role Editor Pro plugin they are hooking into the auto updater using the following filters.
```
add_filter('site_transient_update_plugins', array($this,'injectUpdate')); //WP 3.0+
add_filter('transient_update_plugins', array($this,'injectUpdate')); //WP 2.8+
```
Any ideas how to get these filters to work within the context of a WP-CLI `wp plugin update --all` or even `wp shell`?

**Comment by austinginder** [comment]
Ok after more troubleshooting it appears this plugin is doing a `is_admin()` check before the filters run. That's explains the difference between `update-core.php` and `wp plugin update --all`.

Is there a way to mock and administrator page with WP-CLI? Most of the simple tricks happen to late as far as plugin filters are concerned. I did come up with a hack which involves injecting a mock `current_screen` before WordPress is loaded (see below). I'm wondering if maybe this should be bundled into WP-CLI for these reasons:
-  Better support for 3rd party themes/plugin updates 
-  Closer match the updates of wp-admin

```
function captaincore_mock_admin_page() {

	// Grab WP CLI arguments
	$arguments = WP_CLI::get_runner()->__get( 'arguments' );

	// Mock admin update page when running `wp plugin update` or `wp theme update`
	if ( ( in_array( 'plugin', $arguments ) and in_array( 'update', $arguments ) ) ||
	     ( in_array( 'theme', $arguments ) and in_array( 'update', $arguments ) ) ) {
		require ABSPATH . 'wp-admin/includes/class-wp-screen.php';
		$GLOBALS['current_screen'] = WP_Screen::get( 'update-core' );
	}

}

// Hook in before WP-CLI loads WordPress
if ( defined( 'WP_CLI' ) && WP_CLI ) {
	WP_CLI::add_hook( 'before_wp_load', 'captaincore_mock_admin_page' );
}
```

**Comment by schlessera** [comment]
@austinginder You can try just setting the `WP_ADMIN` constant for that request, like explained here: https://github.com/wp-cli/wp-cli/issues/984#issuecomment-33699111

**Comment by austinginder** [comment]
Just tried using the require argument to set `WP_ADMIN` and it worked! 👍 

Any thoughts on bundling this into `wp plugin update` and `wp theme update`?  I'm good with using the require argument for my use case however a default usage would potentially mean better update coverage for regular usage.

**Comment by austinginder** [comment]
Most of my WP-CLI are done via SSH. It would be amazing if useable without needing to pass an extra file to `--require`. Two ideas to make this more useable.
1. Global argument to quickly define WP_ADMIN `--admin`.
2. Allow `--require` to read from a string. The allow for a small amount of PHP to be run. Example `wp plugin update --all --require="define( 'WP_ADMIN', true );"`.

**Comment by austinginder** [comment]
Understandable. Will look at `WP_CLI_SSH_PRE_CMD`. Currently not using `--ssh=<ssh>` so it would require a rework of my workflow. FYI, i'm using ssh directly as I have great control to run complex multiline scripts remotely as shown in [this example](https://anchor.host/the-best-migrations-happen-between-servers/).

**Comment by vinnyusestrict** [comment]
I was about to open an issue regarding `is_admin()` returning false during `wp plugin de/activate plugin-name` when I found this. My plugin checks for `is_admin()` to be true before calling `register_activation_hook()` or `register_deactivation_hook()` and therefore wasn't working as expected from the command line.

I'm of the opinion that wp-cli should behave like WP when doing admin tasks such as activating, deactivating, and updating plugins.

Keep up the good work!

**Comment by sdenike** [comment]
> Most of my WP-CLI are done via SSH. It would be amazing if useable without needing to pass an extra file to `--require`. Two ideas to make this more useable.
> 
> 1. Global argument to quickly define WP_ADMIN `--admin`.
> 2. Allow `--require` to read from a string. This would allow a small amount of PHP to run before hand. Example `wp plugin update --all --require="define( 'WP_ADMIN', true );"`.

I would love to see this being some sort of -- command that could be ran as I often see issues with various plugins/themes that WP-CLI does NOT update, but of course work fine when logged into the dashboard. eg the --admin argument would be a great addition.

**Comment by ehausen** [comment]
Has this progressed at all? It is pretty serious flaw, that might result in some plugins not to be updated for a long time, if admin wouldn't notice from interface that some plugins actually have updates

**Comment by austinginder** [comment]
I'm opening a separate issue on https://github.com/wp-cli/wp-cli which proposes a new global argument for running generic php code. I think that would satisfy my needs as it relates to this issue however will require some discussion.

@ehausen Currently you can define WP_ADMIN on the fly by doing the following. Create a new PHP file like `require-wp-admin.php` with the content `<?php define( 'WP_ADMIN', true );`. Then when running WP-CLI commands you can require that file like this `wp plugin update --all --require=require-wp-admin.php`.

**Comment by schlessera** [comment]
Note that you can provide default parameters for specific commands via the WP-CLI configuration file:
```
plugin update:
	require: require-wp-admin.php
themeupdate:
	require: require-wp-admin.php
```

**Comment by austinginder** [comment]
With the inclusion of a new global param `--exec` I'll consider this issue closed. See here: https://github.com/wp-cli/wp-cli/pull/5454. Once it's bundled in the next WP-CLI release this new global param will allow for something like this `wp plugin update --all --exec="define( 'WP_ADMIN', true );"` .
