### ISSUE TITLE
update subcommand does not honour the --quiet flag

### ISSUE THREAD

**Issue by dnmvisser** [wp-cli/extension-command#11]
In order to check for updates, I am using the `--quiet` flag to not get any output if there are no updates. 
But the `theme` and `plugin` subcommands always generate output, even when the `--quiet` flag is used. This breaks various wrapper scripts.

Example from an instance that is fully up-to-date:

```
www-data@host:/home/www/www.site.org/wordpress$ wp theme update --all --dry-run
No theme updates available.
www-data@host:/home/www/www.site.org/wordpress$ wp theme update --all --dry-run --quiet
No theme updates available.
```

Note that the `core` subcommand works OK in this respect:
```
www-data@cajones:/home/www/www.site.org/wordpress$ wp core check-update
Success: WordPress is at the latest version.
www-data@host:/home/www/www.site.org/wordpress$ wp core check-update --quiet
www-data@host:/home/www/www.site.org/wordpress$ 
```

**Comment by danielbachhuber** [comment]
Thanks for the report, @dnmvisser 

> But the theme and plugin subcommands always generate output, even when the `--quiet` flag is used.

There are some instances of `WP_CLI::line()` that need to be changed to `WP_CLI::log()`.

Want to submit a pull request?
