### ISSUE TITLE
Add --all option to delete commands

### ISSUE THREAD

**Issue by swissspidy** [wp-cli/extension-command#113]
Right now it's not possible to run something like `wp theme delete --all` or `wp plugin delete --all` to quickly delete all themes and plugins.

I guess my best bet right now is to use the list commands + xargs or something.

`wp plugin uninstall --all` works though, so I think there's some inconsistency.

Edit: #88 already covers `wp plugin delete --all`. My suggestion expands this to the theme command as well.

**Comment by wojsmol** [comment]
Currently I use this to delete inactive themes
```bash
wp theme install ~/test.zip --activate
wp theme delete $(wp theme list --status=inactive --field=name)

```

**Comment by wojsmol** [comment]
Currently I use this to delete inactive themes
```bash
wp theme install ~/test.zip --activate
wp theme delete $(wp theme list --status=inactive --field=name)

```

**Comment by swissspidy** [comment]
@wojsmol Simple & effective!

I wish this would work for the active theme too, see #114.

**Comment by wojsmol** [comment]
In my use-case I use custom theme so #114 in not for me but good addition in general.
