### ISSUE TITLE
Allow `plugin list` to output plugins slugs

### ISSUE THREAD

**Issue by tristanleboss** [wp-cli/extension-command#129]
Hello,

It would be great to allow the command `plugin list` to allow `slug` as a value for the fields parameters.

Command: `wp plugin list --fields=slug`

Expected output:

```
+-------------------------------------------+
| slug                                      |
+-------------------------------------------+
| akismet.php                               |
| hello.php                                 |
| iwp-client/init.php                       |
| plugins-load-order/plugins-load-order.php |
+-------------------------------------------+
```

**Comment by danielbachhuber** [comment]
👍 Seems reasonable. Want to submit a pull request for it?

**Comment by danielbachhuber** [comment]
> There is a risk of having the same slug. Imagine an "hello.php" file in both "plugins" and "mu-plugins" folders. Maybe, adding a "type" (Plugin, MU, Dropin) field could be useful too?

`type` is covered by `status`. We can have some note that indicates `slug` shouldn't be considered a unique value. Or, `slug` could be `file` instead.
