### ISSUE TITLE
PHP Fatal error on Plugin Activation

### ISSUE THREAD

**Issue by anantajitjg** [wp-cli/extension-command#130]
### Summary:

When I activated a plugin, _**PHP fatal error: Call to a member function on null**_, is triggered and that terminated the plugin activation. The same plugin gets activated on Normal WordPress flow without any issues.
	
### Steps to reproduce:

Referring to this plugin: https://github.com/anantajitjg/simple-wp-plugin
In plugin main file, require a class with a condition `is_admin()` and initialize it.
Then call a function of that class on plugin activation
Run `wp plugin activate simple-wp-plugin`
Observe `PHP Fatal Error: Uncaught Error: Call to a member function activate_welcome_page() on null`

### Results

**Expected Results:** Plugin should be activated, Same as the normal WordPress flow

**Actual Results:** Plugin activation terminated

### Relevant diagnostics
![wp-cli](https://user-images.githubusercontent.com/22009263/45476979-072d0580-b75e-11e8-892b-bb45523b7f03.png)
![wp-normal-flow](https://user-images.githubusercontent.com/22009263/45476980-072d0580-b75e-11e8-86ab-7005dfc0a03d.png)

**Comment by schlessera** [comment]
This is a bug in the plugin, not a problem with WP-CLI.

The plugin returns an instantiated object to the activation hook handler. By the time the activation hook gets triggered, PHP has created a new process, so the instantiated object does not exist anymore.

You can only pass static methods or functions to activation handlers, not dynamic methods.

**Comment by swissspidy** [comment]
> I think, in WordPress normal flow, `is_admin()` will return true but when I use wp-cli `is_admin()` is returning false.

Sounds correct to me. You're not really in the admin after all, but in CLI :-) So the plugin shouldn't really assume to be in the admin and load the needed classes / files accordingly.

**Comment by anantajitjg** [comment]
@swissspidy Thanks for the reply. I have found another way; _including admin class on plugin activation_ and to call that specific function and keeping the `is_admin()` check for loading the admin class in the constructor for loading the class for the admin only.
