### ISSUE TITLE
2.0.1 - Error ... theme could not be found

### ISSUE THREAD

**Issue by 16dyui** [wp-cli/extension-command#132]
@dbrosy commented on [Wed Sep 12 2018](https://github.com/wp-cli/wp-cli/issues/4941)

I have upgraded to 2.0.1 and have an issue with activation of a theme.

running the following command on various versions:

wp theme install <url to theme> --activate

1.2.1 Success
2.0.0 Success
2.0.1 Failure

If I remove the --activate than theme installs
After install I run 
wp theme activate Divi and get the following error:

Error: The 'Divi' theme could not be found

This only happens with 2.0.1

---

@jdelvecchio commented on [Wed Sep 12 2018](https://github.com/wp-cli/wp-cli/issues/4941#issuecomment-420635723)

Hi, same error here. Theme cannot be found on activate

---

@16dyui commented on [Fri Sep 14 2018](https://github.com/wp-cli/wp-cli/issues/4941#issuecomment-421233096)

Hi, Theme's name is Internally it is treated in lowercase letters.

```
wp theme install Divin --activate  #can't activate
wp theme install divin --activate  #success
```
Supplement

```
wp theme install Divin
wp theme list
+-----------------+----------+--------+---------+
| name            | status   | update | version |
+-----------------+----------+--------+---------+
| divin           | inactive | none   | 1.1.2   |
+-----------------+----------+--------+---------+
```

---

@16dyui commented on [Fri Sep 14 2018](https://github.com/wp-cli/wp-cli/issues/4941#issuecomment-421234114)

I found Specification change.
[https://github.com/wp-cli/extension-command/pull/126](https://github.com/wp-cli/extension-command/pull/126)

**Comment by schlessera** [comment]
Fixed through #137 with https://github.com/wp-cli/extension-command/releases/tag/v2.0.2

**Comment by freefri** [comment]
This is a critical bug because is not allowing us to update themes with capital letters in their names, trying to run the command with a lower case is not working neither for us. The but is already fixed, but the phar of wp-cli was not updated in 3 months... 
Do we expect any release soon?
We don't feel comfortable using the nightly release in production.

**Comment by schlessera** [comment]
@freefri The next release is scheduled for December 18th: https://make.wordpress.org/cli/2018/10/31/wp-cli-v2-1-0-release-postponed/

In the mean time, you can also roll back to the v2.0.0 release, provided that you don't need the `i18n make-pot` command.
