### ISSUE TITLE
Feature Request: plugin install --must-use option

### ISSUE THREAD

**Issue by acobster** [wp-cli/extension-command#136]
I'd like to be able to run `wp plugin install --must-use some-plugin-slug` and have it install to wp-content/mu-plugins. I'd be happy to work on a PR myself.

**Comment by swissspidy** [comment]
The problem with that is that mu-plugins can‘t be in subfolders like regular ones. Only single PHP files in the mu-plugins folder are loaded.

**Comment by swiftavl** [comment]
Without knowing all the reasons behind previous decisions made regarding the mu-plugins directory, what makes sense to me is to make mu-plugins functionally equivalent to the plugins directory for wp-cli command purposes, so all of the commands below would work.
	wp plugin list
	wp plugin install --must-use some-plugin-slug
	wp plugin activate --must-use some-plugin-slug
	wp plugin deactivate --must-use some-plugin-slug
	wp plugin delete --must-use some-plugin-slug

It may be better to create a separate set of commands
	wp muplugin list
	wp muplugin install
	wp muplugin activate
	wp muplugin deactivate
	wp muplugin delete

Reason for having activate and deactivate is for troubleshooting etc.
It could be as simple as giving mu-plugins an inactive directory called mu-plugins-deactivated.

Install some-plugin-slug into mu-plugins-deactivated/
	wp muplugin install some-plugin-slug

Move some-plugin-slug from mu-plugins-deactivated/ into mu-plugins/
	wp muplugin activate some-plugin-slug
.
.
.
Note issue #25 Listing folders in `muplugins`

**Comment by danielbachhuber** [comment]
Previously
* https://github.com/wp-cli/wp-cli/issues/36
* https://github.com/wp-cli/wp-cli/issues/2041
* https://github.com/wp-cli/ideas/issues/30

Worth noting: For the majority of standard operations (e.g. installing plugins, creating terms, etc.), WP-CLI mirrors what's possible in the WordPress admin. Installing a mu plugin isn't possible in the WordPress admin, so it would fall outside the scope of WP-CLI`*`. More specific to this enhancement, there are multiple ways a plugin can be installed as a mu-plugin, so it's not clear how this would be implemented.

`*` There are clearly some exceptions, but generally this is the guiding rule for scope.

Closing in favor of https://github.com/wp-cli/ideas/issues/30

**Comment by mindfullsilence** [comment]
I know this is old, but there's nothing stopping you from running `wp plugin install some-plugin && mv ./wp-content/plugins/some-plugin ./wp-content/mu-plugins/`

Just be sure to also install something like the Bedrock Autoloader so plugins are loaded from their subfolders
https://github.com/roots/bedrock-autoloader
