### ISSUE TITLE
Enhancement: Plugin and Theme list should alert if the version is HIGHER than found on .org

### ISSUE THREAD

**Issue by Ipstenu** [wp-cli/extension-command#142]
This is a rare-bear problem, but sometimes hackers will bump the version of a hacked plugin so that their backdoor won't get triggered for update and thus delete itself. If the `wp plugin list` command alerted people to "This version is higher than expected..." that might help spot those faster.

**Comment by schlessera** [comment]
Hmm, interesting. I guess such a warning should also be shown on `plugin/theme update` then, as it basically disables that update.

This would also be a good check for the `doctor` command...

**Comment by nylen** [comment]
Bumping the version number to something like `99.0-upstream1.2.3` is the easiest way I'm aware of to fork a plugin for a site without other side effects like breaking translations.

Is there a way to disable this warning in a site's code?

**Comment by schlessera** [comment]
> Is there a way to disable this warning in a site's code?

No, not yet, but it seems it might be needed... Would you mind opening a new issue for this, @nylen, with the use case you mentioned ?

**Comment by nylen** [comment]
Done &rarr; #192
