### ISSUE TITLE
wp plugin update, real versus dry run, inconsistency

### ISSUE THREAD

**Issue by octageeks** [wp-cli/extension-command#160]
Maybe found a bug. Or maybe by design? Hard to tell.

Version WP-CLI 2.1.0

JSON return output differs between dry run and REAL run, when using format option = JSON
Different obj keys/selectors being used.

COMPARE the json out put of these two commands:
'wp plugin update --format=json'
'wp plugin update --dry-run --format=json'

Object keys for REAL run include:
old_version
new_version

Objects keys for DRY RUN include:
version
update_version

var dump, real versus dryrun for comparison:

  object(stdClass)#2 (4) {
    ["name"]=>
    string(20) "wp-live-chat-support"
    ["status"]=>
    string(6) "active"
    ["version"]=>
    string(6) "8.0.23"
    ["update_version"]=>
    string(6) "8.0.24"
  }

  object(stdClass)#2 (4) {
    ["name"]=>
    string(11) "memberpress"
    ["old_version"]=>
    string(6) "1.3.48"
    ["new_version"]=>
    string(5) "1.4.3"
    ["status"]=>
    string(7) "Updated"
  }

This inconsistency breaks our code when we switch between a dry run and real run

**Comment by schlessera** [comment]
@octageeks I'm closing this for now, as I don't think this warrants a change.

Don't hesitate to comment if you think otherwise or have a nice solution ready.

**Comment by octageeks** [comment]
I think your reply is reasonable, I just found this misleading and not the behavior I expected, but there is a lot of room for differing opinions here.

Just my opinion, but I would personally expect "--dry-run" to "simulate" a real run, and that would include keeping the status behavior exactly the same and returning a FALSE POSITIVE as if it worked for real.  

I use --dry-run, for what I assume is its very purpose, to be able to TEST AGAINST it, without actually having a real production effect.   But the way its designed now, it fails me when being used as part of a bash script.

Just me, but I would have added some addition dry run flags, where you could "choose" your "simulated status return", when dry running so I could use --dry-run in actual bash scripts in dry run mode.  I could do unit testing this way without having to code special logic to check for different return statuses.

Does that make sense?

I dont think its a huge issue overall.  Just a philosophical design thing. Being nit picky.

Thanks for the info.
