### ISSUE TITLE
/usr/bin/wp plugin status --allow-root wipes theme data

### ISSUE THREAD

**Issue by Eckybrazzz** [wp-cli/extension-command#163]
I use https://github.com/centminmod on my server and it has a nice and secure option to install WordPress.

Every time when it executes #/usr/bin/wp plugin status --allow-root  it wipes my theme data. My theme is Coupon from https://mythemeshop.com It only wipes the theme settings, nothing else.

```
# /usr/bin/wp plugin status --allow-root
7 installed plugins:
A autoptimize 2.4.4
A cache-enabler 1.3.3
A cdn-enabler 1.0.8
A disable-xml-rpc 1.0.1
A mythemeshop-connect 2.0.14
A sucuri-scanner 1.8.20
D advanced-cache.php
Legend: A = Active, D = Drop-In
```

Please read this tread on the forum:
https://community.centminmod.com/threads/nginx-pagespeed-wordpress-with-redis-cache.17010/page-2#post-72406

```
# wp --info
OS:     Linux 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64
Shell:  /bin/bash
PHP binary:     /usr/local/bin/php
PHP version:    7.2.16
php.ini used:   /usr/local/lib/php.ini
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /root/tools
WP-CLI packages dir:    /root/.wp-cli/packages/
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.1.0
```

**Comment by Eckybrazzz** [comment]
HI @danielbachhuber ,

With "wipes my theme data" I want to say that all that all settings I made inside the theme are gone when running the wp plugin **status** --allow-root. It does not touch post, pages or other created items. Strange that it does it with the "**status**" command, I did not test it with "**update**". As far as I know I'm the only one on the Centmin Mod community that has this problem. I have it running on several domains and for testing I enable or disabled on some domains the wp-cli and could provide the images below quickly. I tested it on the stable release and on the nightly build.

Before it looks like this:
![Screenshot_1](https://user-images.githubusercontent.com/30936842/55650442-218f0500-57bc-11e9-9907-2f23e8ef61cc.png)

Afterwards like this:
![Screenshot_2](https://user-images.githubusercontent.com/30936842/55650466-323f7b00-57bc-11e9-9953-00f47618405e.png)

It is an automated WordPress install with some extra security options. 
![Screenshot_3](https://user-images.githubusercontent.com/30936842/55650870-4df75100-57bd-11e9-9077-1e2c09adc18f.png)
![Screenshot_4](https://user-images.githubusercontent.com/30936842/55650875-50f24180-57bd-11e9-8424-876779020c43.png)

**Comment by danielbachhuber** [comment]
Ok, thanks for the additional information.

The problem is probably specific to your codebase and it's hard to say what that might be without access. Per our [Bug Report Guidelines](https://make.wordpress.org/cli/handbook/bug-reports/), WP-CLI issues are limited to bugs that reproduce the issue in a fresh installation of WordPress and include specific reproduction steps.

**Comment by Eckybrazzz** [comment]
Adding --skip-themes resolved it for now.
