### ISSUE TITLE
Add --network option to plugin install --activate

### ISSUE THREAD

**Issue by modelm** [wp-cli/extension-command#165]
I can install & activate a plugin on a single site in a single step like this:
```
wp plugin install --activate query-monitor
```

But because `--network` is not handled by `plugin install`, I can't simultaneously install & network-activate the same plugin on a multisite network:
```
wp plugin install --activate --network query-monitor
Error: Parameter errors:
 unknown --network parameter
```

The shortest way I can find is to do it in two steps:

```
wp plugin install query-monitor
wp plugin activate --network query-monitor
```

It would be nice to be able to install & network-activate a plugin in one step.

**Comment by danielbachhuber** [comment]
I'm not quite sure when it was implemented compared to when this issue was opened, but `wp plugin install` supports an `--activate-network` argument.
