### ISSUE TITLE
The "wp theme search" command has not the "page" option 

### ISSUE THREAD

**Issue by amieiro** [wp-cli/extension-command#166]
In the WP-CLI 2.1.0 I was checking the commands "wp plugin search" and "wp theme search". I have found that both have the "--per-page" option (optional number of results to display), but the "--page" option it is only shown in the plugin command.

So, you can execute

```
wp plugin search contact-form-7 --per-page=20 --page=3 --fields=slug,rating
```
but you can't execute

```
wp theme search woocommerce --per-page=20 --page=3 --fields=slug,rating,preview_url
```

It gives an error:

```
Error: Parameter errors:
unknown --page parameter
```

I suppose this is a bug because it is a no sense that you can indicate the size of the page search but you can't indicate the page you want to get.

**Comment by schlessera** [comment]
Fixing this is just a matter of adding the `[--page]` flag to the docblock of the theme search command and then regenerating the README.md file.

**Comment by amieiro** [comment]
I close the issue because the PR that solve it has been merged https://github.com/wp-cli/extension-command/pull/167
