### ISSUE TITLE
PHP-Notice: undefined index 'package' for `wp plugin list`

### ISSUE THREAD

**Issue by mravery** [wp-cli/extension-command#171]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bg reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

A clear and concise description of the behavior that produces a wrong result or error.

Remember to provide some context to make sure we're all on the same page when reasoning about this.

**Describe how other contributors can replicate this bug**

- a list of
- steps to replicate
- the error condition

```js
// You can also use code snippets if needed.
```

**Describe what you would expect as the correct outcome**

A clear and concise description of what you expected to happen (or code).

**Let us know what environment you are running this on**

```
(Paste the output of "wp cli info" into this box)
```

**Provide a possible solution**

If you happen to have a suggestion on how to fix this bug, please tell us in here.

Just leave this section out if you don't know how to fix it.

**Provide additional context/Screenshots**

If applicable, add screenshots to help explain (you can just drag&drop images into the Github issue).

**Comment by schlessera** [comment]
@mravery I cannot replicate this on my side. Unless you provide more details (like the actual error output), I have to assume this is just a plugin `doing_it_wrong()`...

**Comment by mravery** [comment]
Sorry I hit the submit button too quickly.

**Comment by mravery** [comment]
Please close/delete this. It was an environment issue; the problem isn't manifesting itself any more.

**Comment by roopemerikukka** [comment]
This is happening for me as well. The problem occurs in this line: https://github.com/wp-cli/extension-command/blob/master/src/Plugin_Command.php#L663 when I'm trying to list the plugins (or do anything plugins related). It seems that `polylang-pro` plugin causes that problem. The issue is that I'm running these commands in deployment pipeline and it fails because the wp-cli returns an error code != 0 :/
