### ISSUE TITLE
Namespaces

### ISSUE THREAD

**Issue by MacGyer** [wp-cli/extension-command#174]
- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

As namespaces are common since a while in PHP now, are there any plans to release a namespaced version of the package?

**Describe the solution you'd like**

Source with namespaced PHP files.

Thanks.

**Comment by danielbachhuber** [comment]
Thanks for the question, @MacGyer !

There aren't any plans to release a namespaced version of the package.
