### ISSUE TITLE
Plugin is not activated when it is already installed

### ISSUE THREAD

**Issue by ernilambar** [wp-cli/extension-command#176]
**Case 1: When plugin is not installed**

`$ wp plugin install woocommerce --activate`

```
Installing WooCommerce (3.6.2)
Downloading installation package from https://downloads.wordpress.org/plugin/woocommerce.3.6.2.zip...
Using cached file '/home/nilambar/.wp-cli/cache/plugin/woocommerce-3.6.2.zip'...
The authenticity of woocommerce.3.6.2.zip could not be verified as no signature was found.
Unpacking the package...
Installing the plugin...
Plugin installed successfully.
Activating 'woocommerce'...
Plugin 'woocommerce' activated.
Success: Installed 1 of 1 plugins.
```

**Case 2: When plugin already exists but is inactive**

`$ wp plugin install woocommerce --activate`

```
Warning: woocommerce: Plugin already installed.
Success: Plugin already installed.
```

I believe in case 2 also, plugin should be activated.

Environment:

```
OS: Linux 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64
Shell:  /bin/bash
PHP binary: /usr/bin/php7.2
PHP version:    7.2.17-0ubuntu0.18.04.1
php.ini used:   /etc/php/7.2/cli/php.ini
WP-CLI root dir:    phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:  phar://wp-cli.phar/vendor
WP_CLI phar path:   /var/www/review.dev/public_html/wp-content/themes
WP-CLI packages dir:    /home/nilambar/.wp-cli/packages/
WP-CLI global config:   /home/nilambar/.wp-cli/config.yml
WP-CLI project config:  
WP-CLI version: 2.2.0
```

**Comment by wojsmol** [comment]
@ernilambar For case 2 use `wp plugin activate woocommerce`.

**Comment by ernilambar** [comment]
> @ernilambar For case 2 use `wp plugin activate woocommerce`.

Yes, I know but when command is to install and activate then both installation and activation should be done by the command. I believe this is the expected behavior.

**Comment by ernilambar** [comment]
FYI: I checked this in WP CLI 2.1 and it is working as expected. I guess it came due to some regression in WP CLI 2.2.

**Comment by schlessera** [comment]
This regression was likely introduced here: https://github.com/wp-cli/extension-command/pull/146/files#diff-279741d45b2acc7ffd7535587e339c96R216

For fixing this, we should add a regression test first to make sure we cannot break that again in the future.
