### ISSUE TITLE
Using --exclude on plugin update results in a parameter error

### ISSUE THREAD

**Issue by richardlampitt** [wp-cli/extension-command#178]
When using the --exclude flag whilst trying to update plugins, CLI gives an error. 

Steps to reproduce:
1: On the command line, run the command "wp plugin update --exclude=advanced-custom-fields --all"
2: The command will fail, with an error message:
"Error: Parameter errors:
 unknown --exclude parameter" (sic)

**Comment by shaneonabike** [comment]
You actually have to reverse the commands it works. wp plugin update --all -exclude=advanced-custom-fields

**Comment by danielbachhuber** [comment]
`wp plugin update --exclude=elementor --all` seems to work just fine for me
