### ISSUE TITLE
List dropin plugins in wp plugin list

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/extension-command#18]
I just had a need to find out whether the `db.php` dropin plugin was in place on a site, but couldn't do it via WP-CLI because dropins aren't listed as part of `wp plugin list`.

I wonder if the command should behave in the same way as the Plugins screen in the admin area, whereby you have to go to the Dropins tab to see dropin plugins. The WP-CLI equivalent would be that you need to pass the dropins status flag to see dropins listed:

    wp plugin list --status=dropins

**Comment by danielbachhuber** [comment]
We're already including mu plugins in `wp plugin list`, so I'd be amenable to including dropins too, with `status=>dropin`

`--status=dropin` as an argument would filter the list to solely dropins.
