### ISSUE TITLE
`wp plugin update --all` reports false positive update "status" when local version is higher than repo

### ISSUE THREAD

**Issue by mrwweb** [wp-cli/extension-command#187]
## Bug Report
- [X] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [ ] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**
Definitely Related: #142 
Maybe Related: #175

It's not all that uncommon to run a version of a plugin (or theme) that is higher than the version in the repository. In my case, I'm running one more-recent version of a plugin from Github that hasn't been released in the repo and a personal copy of a plugin with numerous bug fixes that I haven't been able to get merged.

```console
$ wp plugin update --all
The plugin is at the latest version.
The plugin is at the latest version.
+---------------------+-------------+-------------+---------+
| name                | old_version | new_version | status  |
+---------------------+-------------+-------------+---------+
| content-audit-FIXES | 2.0a        |             | Updated |
| wp-help-master      | 1.6.0-beta1 |             | Updated |
+---------------------+-------------+-------------+---------+
Success: Updated 2 of 2 plugins.
```

**Describe how other contributors can replicate this bug**

1. Bump the Version number of any plugin in the repo so it's higher than the latest version
1. `$ wp plugin update --all`
1. result name shows "Updated"

**Describe what you would expect as the correct outcome**

WP-CLI should report that the plugin version is higher than expected _and no action was taken._

**Let us know what environment you are running this on**

```
OS:     Linux 4.9.93-boot2docker #1 SMP Thu Jul 19 18:29:50 UTC 2018 x86_64
Shell:
PHP binary:     /opt/php/7.2.0/bin/php
PHP version:    7.2.0
php.ini used:   /conf/php/7.2.0/php.ini
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:  //wp-cli.yml
WP-CLI version: 2.2.0
```

**Provide a possible solution**

Using example from the above and taking inspiration from `$ wp plugin list`:

```console
$ wp plugin update --all
Warning: Version higher than expected.
Warning: Version higher than expected.
Error: No plugins updated.
```

**Comment by schlessera** [comment]
Yes, this is a bug indeed. I assume the status check just acts on the two versions being "different", without qualifying further.

**Comment by jasomdotnet** [comment]
Still and issue in 2020.

**Comment by montaniasystemab** [comment]
I can confirm this is an issue with themes as well, wp-cli 2.4.0 up to date: 

```
$ wp theme list
+----------------+----------+------------------------------+---------+
| name           | status   | update                       | version |
+----------------+----------+------------------------------+---------+
| flatsome-old   | inactive | version higher than expected | 3.9.0   |
| flatsome       | active   | version higher than expected | 3.11.1  |
| twentynineteen | inactive | version higher than expected | 1.4     |
| twentytwenty   | inactive | version higher than expected | 1.1     |
+----------------+----------+------------------------------+---------+
```
