### ISSUE TITLE
Unexpected results from executing "wp theme search"

### ISSUE THREAD

**Issue by tecking** [wp-cli/extension-command#188]
An unexpected result was encountered when executing `wp theme search`.

I executed the following command.

``wp theme search wordpress --field=slug``

I expected...

```
Success: Showing 0 of 0 themes.
```

Because I understand that [_wordpress_ should not be used in a theme slug.](https://make.wordpress.org/themes/handbook/review/required/)

But, the result was...

```
Success: Showing 10 of 2839 themes.
busiup
envo-ecommerce
consultup
sirat
insights
empowerwp
busimax
innofit
knight
jinsy-magazine
```

What does the ``--field=slug`` option refer to?

**Comment by schlessera** [comment]
The `--field=slug` defines what field to show for each of the results, not what to search against.

What is actually being searched is up to the API endpoint on wordpress.org that is being used for this functionality.

My guess is that you're finding all themes that have the `wordpress` term in their description.

Please note that GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. If you need help with general usage, please join us in the #cli channel on the official make.wordpress.org Slack team.
