### ISSUE TITLE
Allow to install plugin from unsafe source

### ISSUE THREAD

**Issue by alexander-akait** [wp-cli/extension-command#189]
## Feature Request

Add option to install plugins/themes from unsafe source.

**Is your feature request directly related to a specific, existing command?**

yes

**Is your feature request about a new command, or a more general idea?**

just flag

--- ✅ If you are in the correct location now... ---> 

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

A clear and concise description of what you are actually trying to do, and in what way the current version of WP-CLI is not up to the task.

```sh
wp plugin install https://gitlab.itgalaxy.company/itgalaxy/insteria-contact/-/archive/master/insteria-contact-master.zip
```

The `gitlab.itgalaxy.company` domain is gitlab self-hosted.

**Describe the solution you'd like**

Just add flag `--allow-unsafe-url` (maybe best name). For example:
```
wp plugin install https://gitlab.itgalaxy.company/itgalaxy/insteria-contact/-/archive/master/insteria-contact-master.zip --allow-unsafe-url
```

I can send a PR if you accept this, thanks

**Comment by schlessera** [comment]
I'm not sure I understand your issue correctly. Installing a plugin from a Gitlab link like above already works:
![Image 2019-08-06 at 1 50 44 PM](https://user-images.githubusercontent.com/83631/62537637-32768280-b851-11e9-9e49-f81190d179bb.png)

I guess you might have a different problem, though, namely that your curl is not set up properly to be able to deal with the HTTPS protocol. That is unrelated to installing plugins, and more of a general environment problem. Can you post the exact output you are getting?

**Comment by evilebottnawi** [comment]
> I guess you might have a different problem, though, namely that your curl is not set up properly to be able to deal with the HTTPS protocol

No, we success install from github, here problem:
- https://github.com/WordPress/WordPress/blob/8ab7bbe3857ceb5206f9caffcbf73580adf011c3/wp-includes/class-http.php#L264

**Comment by schlessera** [comment]
Again, I think you're misunderstanding the problem here. There is no "safe source" in terms of downloading WordPress plugins, WordPress does not care at all where you get your plugins from.

What you are dealing with is a URL that is being parsed as being invalid, so it will not work to download the file either way. This is very probably due to either your cURL being incorrectly configured, or your hosts/proxy files being misconfigured on your server/machine.

**Comment by evilebottnawi** [comment]
@schlessera why when i debug this problem i have problem there https://github.com/WordPress/WordPress/blob/cff445d55f9bd53b608d3b9247ef62129aa9a816/wp-admin/includes/file.php#L1009, but if i comment `reject_unsafe_urls` hoos all works fine, i can't see here problem with curl, also fetching from github?
