### ISSUE TITLE
Support multiple values on "plugin list --status=X"

### ISSUE THREAD

**Issue by Athanasius** [wp-cli/extension-command#194]
## Feature Request

I wish to find all *not* inactive plugins and themes for a site.  If I use "wp plugin list --status=active" I'll miss any that are "active-network", and vice versa. I'm using "--format=json" so can't simply grep the output lines.

Obviously I could pass the JSON output through something like jq as a workaround, but the ability to do something like "wp plugin list --status=active,active-network" would negate the need for the extra processing.  Alternatively "wp plugin --status=!inactive" or the like would also work.

Yes, some care needs to be taken with the separator or negation operator to ensure they're not legal characters in WP plugins (or themes).

**Comment by schlessera** [comment]
I think it makes sense to accept a comma-separated list here for multiple status values.

Would you be interested in providing a pull request for this, @Athanasius ?

**Comment by Athanasius** [comment]
Given my use case "--status=!inactive" would be the more useful, although I'm sure others would have use cases for multiple positive filters.

Unfortunately the whole reason I was using WP CLI in the first place was so as to avoid needing to develop in PHP.  I'm unqualified to provide a patch for this.

**Comment by schlessera** [comment]
`--status=!inactive` will be more difficult to parse and will not as easily be adapted for other flags/commands. Allowing for a set of multiple elements as a first iteration is much more straight-forward in terms of implementation.

> Unfortunately the whole reason I was using WP CLI in the first place was so as to avoid needing to develop in PHP. I'm unqualified to provide a patch for this.

That's perfectly fine! We'll see whether other people might find inspiration here to provide a patch. Given the usefulness and applicability to other commands, I might even consider writing this one myself if I find the time.

**Comment by xyulex** [comment]
I would like to give it a go. It's the first issue I am trying to do, so be patient... :)

**Comment by schlessera** [comment]
@xyulex Yes, no problem. Just let me know if you need assistance.

**Comment by xyulex** [comment]
I have started having a look at it and found where WPCLI return all the status for a certain plugin but can't find where does it do the filtering for showing the final table at the formatter.

**Comment by schlessera** [comment]
The filtering should be happening here:

https://github.com/wp-cli/extension-command/blob/master/src/WP_CLI/CommandWithUpgrade.php#L488-L493

**Comment by xyulex** [comment]
OK, thanks, I just found it.

**Comment by xyulex** [comment]
@schlessera I have a version of it working on my local machine. I have two questions:

- Would you like to get the file before I do a pull request?
- Do I have to modify something more, like unit tests or something?

**Comment by schlessera** [comment]
@xyulex You seem to be on the right track (from what I can see in the commits here), but you're removing the original logic in the process. This breaks everything _but_ the status field.

You need to _add_ to the existing logic, instead of _replacing_ it.

**Comment by xyulex** [comment]
The first commit broke everything, then I checked if the parameter was 'status'. I think that's corrected in ( #edcf08 ). At least, the commands work on it. I will keep checking it. Thanks for your feedback.
