### ISSUE TITLE
Include `update_version` in default plugin list and theme list fields

### ISSUE THREAD

**Issue by lkraav** [wp-cli/extension-command#198]
## Feature Request

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

`wp plugin list --update=available` fails to display what version updates are available.

**Describe the solution you'd like**

`wp plugin list --update=available --fields=name,status,update,version,update_version` works as desired, which made me wonder why `update_version` field isn't part of the default output set?

I am aware of `update_version` possibly being subject to a race condition, where a plugin author may upload a newer version during the time to user executing the actual `wp plugin update` command. Still feels like seeing `update_version` has more benefits than drawbacks.

Your thoughts?

**Comment by iandunn** [comment]
That'd be useful to me too. I think it's worth adding to the default output of the plain `wp plugin list` command too.

**Comment by siilike** [comment]
This would be a significant usability improvement.

**Comment by danielbachhuber** [comment]
I'm open to it, if someone would like to submit a PR for it. We should probably change `wp theme list` too, for parity.

**Comment by swissspidy** [comment]
If someone is looking for inspiration, in #379 I ended up with a related change by adding `auto_update` to the default plugin and theme list output. Might be useful here.

**Comment by sejas** [comment]
I would like to work on this issue during the `#hackday`
@swissspidy , thanks for pointing to the PR for inspiration 👍

**Comment by danielbachhuber** [comment]
🚢
