### ISSUE TITLE
Getting theme list very slow

### ISSUE THREAD

**Issue by Feriman22** [wp-cli/extension-command#202]
I have a WordPress Multisite with 172 installed themes. Checking theme updates with this below command is very slow:

`wp theme list --update=available`

It’s loading for 2-3 minutes and then show the result.
When I check the same on WordPress Dashboard, it takes only 2-3 seconds (Updates subpage).

Is it works as designed or something is wrong with the command?

Thanks!

**Comment by LC43** [comment]
i confirm this behaviour. on a multisite, the lookup is extremely sluggish

**Comment by nimjitzu** [comment]
I am also experiencing very slow performance with 

wp theme list --status=active --field=name

Multisite v 6.0.3
109 themes

**Comment by danielbachhuber** [comment]
This seems to be an environment-specific issue. Feel free to stop by the `#cli` channel on [WordPress.org Slack](https://make.wordpress.org/chat/) if you'd like help debugging further.
