### ISSUE TITLE
Add --format option to plugin status

### ISSUE THREAD

**Issue by nbyloff** [wp-cli/extension-command#205]
## Feature Request

- [X] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

I have an automated script that monitors plugins, wp core, to make sure they're up to date and have the correct checksum. If something isn't correct, I want to send the output in an email. 

But when I send the stdout response from `wp plugin status` in an email it has weird formatting that makes it hard to read outside the CLI. All single line with weird characters (changes slightly based on where it's being viewed).

````
5 installed plugins: A advanced-custom-fields-pro[0m 5.8.7 A autodescription [0m 4.0.4 A zoho-campaigns [0m 2.0.2 [36mM bedrock-autoloader [0m 1.0.0 [36mM disallow-indexing [0m 1.0.0 Legend: A = Active[0m, [36mM = Must Use[0m\n 
````

I'd like to be able to run `wp plugin status --format=json` or something like that so I can parse the data and generate the proper HTML output for email.

**Comment by toddr** [comment]
I have the same need for `wp --format=json plugin auto-updates status --all` as well as `themes`.

I would LOVE for JSON to be an available format. In the meantime, I'm using the environment variable `SHELL_PIPE=1` to coerce the output into a tab-delimited output I can more easily parse.

**Comment by danielbachhuber** [comment]
@toddr @nbyloff Out of curiosity, what does `wp plugin status` offer you that `wp plugin list` does not?

**Comment by toddr** [comment]
>  Out of curiosity, what does wp plugin status offer you that wp plugin list does not?
There is no `plugin auto-updates list` command :( 

```plugin auto-updates status --all```

**Comment by nbyloff** [comment]
> @toddr @nbyloff Out of curiosity, what does `wp plugin status` offer you that `wp plugin list` does not?

For me, they both have an indicator on whether a plugin update is available or not, so I could use either one. However it does not make it easy if I want to get the results programmatically. Example of how I'd like to run it:

````
$status = \WP_CLI::run_command('plugin list --format=json');
 // parse plugin status and send notifications if necessary     
````

**Comment by mrsdizzie** [comment]
For parsing plugins in PHP, this should already work how you would like to run it and is easy to use programmatically:

```php
$options = array(
  'return'       => true,                // Return 'STDOUT'; use 'all' for full object.
  'parse'        => 'json',              // Parse captured STDOUT to JSON array.
);
$plugins = \WP_CLI::runcommand('plugin list --format=json', $options);

foreach ($plugins as $plugin) {
    if ( "available" === $plugin['update'] ) {
        echo "Update available for " . $plugin['name'] . PHP_EOL;
    }
}
```

**Comment by danielbachhuber** [comment]
Building off @mrsdizzie's suggestion, you can use the `--fields=` argument to specify the fields you'd like:

```
$ wp plugin list --fields=name,status,update,auto_update
+--------------------+----------+--------+-------------+
| name               | status   | update | auto_update |
+--------------------+----------+--------+-------------+
| newspack-ads       | inactive | none   | off         |
| wordpress-importer | inactive | none   | off         |
| local              | must-use | none   | off         |
+--------------------+----------+--------+-------------+
```

**Comment by nbyloff** [comment]
@mrsdizzie @danielbachhuber It's been so long since I messed with this I didn't know about these options. Thanks for this!
