### ISSUE TITLE
Allow theme mods for non-active themes to be managed

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/extension-command#208]
Theme mods are stored as a serialized option specific to each theme. It should be possible to allow management of the theme mods of themes that aren't active.

For example, I'd like to read the value of a theme mod of a previous theme.

How about a `[--theme=<theme>]` flag for all the `wp theme mod` commands?

**Comment by danielbachhuber** [comment]
@johnbillion What's the specific use case here? I'm not opposed, but maybe you could use `wp option` instead?

**Comment by johnbillion** [comment]
I can't remember what exactly I was working on, but I believe I had switched themes and then wanted to read the theme mod values from the previous theme.

Happy to close this off.

**Comment by danielbachhuber** [comment]
👍 

We can re-open if it comes up for someone else again.
