### ISSUE TITLE
Autocomplete for plugin and theme names

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/extension-command#21]
It would be great if typing `wp plugin activate a`<kbd>tab</kbd> would invoke autocomplete for the plugin name.

Affected commands for plugins and themes: `activate`, `deactivate`, `delete`, `get`, `is-installed` (self-defeating, but hey), `path`, `status`, `toggle`, `uninstall`, `update`.

**Comment by schlessera** [comment]
I like the idea, it would certainly make some of the more common steps like (de)activation less of a hassle.

**Comment by danielbachhuber** [comment]
Previously https://github.com/wp-cli/wp-cli/issues/1006, notably:

> The only drawback would be that completions wouldn't be as snappy, since we'd have to load WordPress.

**Comment by johnbillion** [comment]
The ideal situation would be to load WordPress on demand when the autocompletion context requires it. No idea how workable that is.

**Comment by danielbachhuber** [comment]
Closing this as `maybelater`. I don't think it's feasible to load WordPress in the autocompletion process, but I'd be happy to be proven wrong.
