### ISSUE TITLE
Bug: `wp theme update --dry-run` runs actual update, not dry run

### ISSUE THREAD

**Issue by mrwweb** [wp-cli/extension-command#210]
## Bug Report

**Describe the current, buggy behavior**

I just ran the following command:

`wp theme update chaplin --version=2.0.4 --dry-run`

Much to my surprise this was the output:

> Installing Chaplin (2.0.4)
> Downloading installation package from https://downloads.wordpress.org/theme/chaplin.2.0.4.zip...
> Unpacking the package...
> Installing the theme...
> Removing the old version of the theme...
> Theme updated successfully.
> Success: Installed 1 of 1 themes.

After checking, I can confirm that the theme was in fact updated on the server.

Possibly relevant, this was a downgrade from v2.1.3 of the theme.

**Provide additional context/Screenshots**

WP 5.3.2 with wp-cli 2.4 on SiteGround

**Comment by schlessera** [comment]
The `theme update` command has a hard-coded update path for the `--version` flag. This is indeed missing a check for `--dry-run`.

The code should check if `--dry-run` and `--version=<version>` are used at the same time, and throw a `WP_CLI::error()` that `--dry-run` cannot be used when specifying a specific version (it would not do much anyway, except for posting the version that was specified with `--version=<version>`).

**Comment by vsamoletov** [comment]
Working on this one
