### ISSUE TITLE
Add readme.txt validator

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/extension-command#221]
## Feature Request

`wp plugin validate-readme $PLUGIN-NAME`

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

Validate readme.txt and display notices, warnings and errors.

**Describe the solution you'd like**

code from https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/plugins/plugin-directory/readme

**Comment by swissspidy** [comment]
There are now https://github.com/swissspidy/validate-readme-command and https://github.com/WordPress/plugin-check (also has a WP-CLI command) now that both offer this.
