### ISSUE TITLE
Consider supporting a new option to clone when installing from source

### ISSUE THREAD

**Issue by aaemnnosttv** [wp-cli/extension-command#223]
## Feature Request

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

When installing a new extension from source, WP CLI currently only offers a way to install the distributable. However, for developers we often want to install the extension from source (i.e. git clone) to submit a contribution, etc.

**Describe the solution you'd like**

I'm suggesting we add a new option to the `{plugin|theme} install` commands which installs the full source rather than just the dist/zip artifact. Composer has a similar option for it's `create-project` command called `--keep-vcs`. The idea is the same 😄

**Comment by swissspidy** [comment]
I think if you want to download an plugin/theme from a repository to contribute to it etc., it's just easiest to simply `git clone` that repo yourself. You don't need WP-CLI for that :-)
