### ISSUE TITLE
Install a plugin with --activate flag can fail between the two actions

### ISSUE THREAD

**Issue by mircobabini** [wp-cli/extension-command#230]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

I run a `plugin install --activate` with the plugin name instead of the plugin slug. Weird but it partially worked, in fact it installed the plugin but not activated it (because not found).

```
public_html$ wp plugin install --activate "GD Mail Queue"
Installing GD Mail Queue (3.4.2)
Scaricando pacchetto di installazione da https://downloads.wordpress.org/plugin/gd-mail-queue.zip...
Scompattamento del pacchetto...
Installazione plugin...
Plugin installato correttamente.
Warning: The 'GD Mail Queue' plugin could not be found.
Success: Installed 1 of 1 plugins.
```

**Describe how other contributors can replicate this bug**

Just run the command above.

**Describe what you would expect as the correct outcome**

I expect it to fail immediately. Or to work completely.

**Let us know what environment you are running this on**

```
OS:	Linux 3.12.18-clouder0 #1 SMP Tue Oct 9 18:14:47 EEST 2018 x86_64
Shell:	/bin/bash
PHP binary:	/usr/local/php73/bin/php-cli
PHP version:	7.3.16
php.ini used:	/usr/local/php73/lib/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/home/customer/www/hidden-site-name/public_html
WP-CLI packages dir:	/home/u2-fakedusername/.wp-cli/packages/
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	2.4.0
```

**Comment by swissspidy** [comment]
The `wp plugin install` command actually expects a plugin slug or ZIP URL. It's just coincidence that the WordPress.org plugins API ends up finding the right plugin with the right slug.

I think I'd be open to a PR that uses that slug to then activate the plugin, but it could just as well be considered an unsupported case.

**Comment by mircobabini** [comment]
Me in 2023 thinks it's ok to be just unsupported.
