### ISSUE TITLE
Add ability to activate all recently active plugins

### ISSUE THREAD

**Issue by timothyjensen** [wp-cli/extension-command#232]
## Feature Request

In the WordPress admin it is possible to list all recently active plugins on the plugins screen, and from there to activate all those recently active plugins. Often times when troubleshooting, deactivate all plugins using WP CLI, but to re-activate them I have to leave the command line and go to the plugins screen. It would be great if I could remain in the command line to reactivate the recently active plugins.

I am imagining a `--recently-active` flag that could be used with `list` or `activate`.

**Comment by danielbachhuber** [comment]
This sounds like a good idea!  Feel free to submit a pull request, if you'd like. Here is some [guidance on our pull request best practices](https://make.wordpress.org/cli/handbook/contributions/pull-requests/).

**Comment by ernilambar** [comment]
Fixed in https://github.com/wp-cli/extension-command/pull/424
