### ISSUE TITLE
plugin delete hangs when file permissions forbid the operation 

### ISSUE THREAD

**Issue by slavicd** [wp-cli/extension-command#238]
## Bug Report

**Describe the current, buggy behavior**

Attempting `wp plugin delete foo` will result in wp-cli hanging if there are file permission issues (say, no write access).

**Describe what you would expect as the correct outcome**

I expect to see an error message where wp-cli's process has no right access to accomplish the operation.

**Let us know what environment you are running this on**

```
OS:	Linux 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64
Shell:	/bin/bash
PHP binary:	/usr/bin/php7.3
PHP version:	7.3.14-1~deb10u1
php.ini used:	/etc/php/7.3/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/var/www/[edited]
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	2.4.0

```

**Comment by danielbachhuber** [comment]
Thanks for the report, @slavicd.

I confirmed the problem and submitted a fix: https://github.com/wp-cli/extension-command/pull/376
