### ISSUE TITLE
Incorrect "Success" message for wp plugin delete if plugin doesn't exist

### ISSUE THREAD

**Issue by mrwweb** [wp-cli/extension-command#24]
Using WP v4.8 & CLI v1.2.0

I forgot Hello Dolly's slug on a new install and got the following:

```
$ wp plugin delete hello-dolly
Warning: The 'hello-dolly' plugin could not be found.
Success: Plugin already deleted.
```

Problem: Get a "success" error whenever the plugin slug doesn't exist in `wp plugin delete {slug}`

Expected: Message saying plugin does not exist so not deleting anything. Possibly suggest you check the slug.

**Comment by danielbachhuber** [comment]
Hi @mrwweb,

Thanks for the report. This was actually an intentional design decision. You can see more of the history in this thread: https://github.com/wp-cli/wp-cli/issues/3577
