### ISSUE TITLE
Include more information with wp plugin list

### ISSUE THREAD

**Issue by RoundAboutWEB** [wp-cli/extension-command#241]
It would be very helpful for security if plugin and theme list would also show the age of a plugin/theme and with which version of wordpress (Tested up to) it was tested.

```
+----------------------------------+----------+------------------------------+----------+--------------+------------+
| name                             | status   | update                       | version  | Tested up to | Date       |
+----------------------------------+----------+------------------------------+----------+--------------+------------+
| adminimize                       | active   | none                         | 1.11.6   | 5.4.2        | 23.12.2019 |
+----------------------------------+----------+------------------------------+----------+--------------+------------+
```

**Comment by RoundAboutWEB** [comment]
Is this optimization feasible or do I need to think of another solution without wp-cli to do this?

**Comment by ernilambar** [comment]
`Tested up to` value of plugin is obtained from the readme file. Currently we are using plugin headers from main plugin file only for the output. Reading that value would require implement Readme Parser like it is done in the WordPress Plugin Directory. Not sure it is worth adding such parser to display only that one value.

CC @danielbachhuber

**Comment by danielbachhuber** [comment]
I'm open to considering a PR for this. It could be a good contributor day issue.

**Comment by tfirdaus** [comment]
@danielbachhuber following up on the PR #413, as I encountered with some issues with getting dependencies working. I'd hold it off for the moment, and would probably discuss this on the Hack day.

**Comment by danielbachhuber** [comment]
@tfirdaus Sounds good!
