### ISSUE TITLE
--continue-anyway or similar option added to "plugin update --all"

### ISSUE THREAD

**Issue by buanzo** [wp-cli/extension-command#242]
Hi.

**Describe your use case and the problem you are facing**

I use wp-cli plugin update --all extensively. When there is an error with a plugin in relation to 'version higher than expected', wp-cli stops execution and the other plugins do not get updated.

**Describe the solution you'd like**

I would like a flag that modifies that behavior, allowing the user to choose if to continue updating other plugins or exit.

Thank you for considering my issue.

**Comment by kkmuffme** [comment]
In my opinion this should even be the default behavior

**Comment by jasomdotnet** [comment]
I have same problem (update process) and I agree on both. If not default behaviour than at least add `--confinue-anyway` flag.

**Comment by danielbachhuber** [comment]
This should be addressed with https://github.com/wp-cli/extension-command/pull/338
