### ISSUE TITLE
Installing an earlier version of a plugin results in duplicated folder

### ISSUE THREAD

**Issue by adekbadek** [wp-cli/extension-command#244]
## Bug Report

- [X] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [X] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

Installing an earlier version of a plugin from Github causes folder duplication.

**Describe how other contributors can replicate this bug**

- Install a latest version of a plugin:

```
wp plugin install https://github.com/Automattic/newspack-ads/releases/latest/download/newspack-ads.zip
```

<details>
<summary>
output
</summary>
<pre>
Downloading installation package from https://github.com/Automattic/newspack-ads/releases/latest/download/newspack-ads.zip...
Unpacking the package...
Installing the plugin...
Renamed Github-based project from 'newspack-ads-c5qcHi' to 'newspack-ads'.
Plugin installed successfully.
Success: Installed 1 of 1 plugins.
</pre>
</details>

- now force-install an earlier version of the plugin:

```
wp plugin install https://github.com/Automattic/newspack-ads/releases/download/v1.4.1/newspack-ads.zip
```

<details>
<summary>
output
</summary>
<pre>
Downloading installation package from https://github.com/Automattic/newspack-ads/releases/download/v1.4.1/newspack-ads.zip...
Unpacking the package...
Installing the plugin...
Plugin installed successfully.
Success: Installed 1 of 1 plugins.
</pre>
</details>

- there are now two copies of the plugin:

```
| newspack-ads-nmHb9h           | inactive | none      | 1.4.1          |
| newspack-ads                  | active   | none      | 1.4.2          |
```

**Describe what you would expect as the correct outcome**

I'd expect installing an earlier version to work just as installing a newer version. The outcome should be a single plugin folder, with the installed version of the plugin.

**Let us know what environment you are running this on**

<details>
<summary>
cli info
</summary>
<pre>
OS:	Linux 4.15.0-111-generic #112-Ubuntu SMP Thu Jul 9 20:32:34 UTC 2020 x86_64
Shell:	/bin/bash
PHP binary:	/usr/bin/php7.2
PHP version:	7.2.32-1+ubuntu18.04.1+deb.sury.org+1
php.ini used:	/etc/php/7.2/cli/php.ini
MySQL binary:	/usr/bin/mysql
MySQL version:	mysql  Ver 15.1 Distrib 10.3.23-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
SQL modes:	STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/srv/www/newspack
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:	/srv/www/newspack/wp-cli.yml
WP-CLI version:	2.5.0-alpha-75cb7e3
</pre>
</details>

**Comment by danielbachhuber** [comment]
@adekbadek I think this bug has since been fixed:

```
$ wp plugin install https://github.com/Automattic/newspack-ads/releases/latest/download/newspack-ads.zip
Downloading installation package from https://github.com/Automattic/newspack-ads/releases/latest/download/newspack-ads.zip...
Unpacking the package...
Installing the plugin...
Plugin installed successfully.
Success: Installed 1 of 1 plugins.
$ wp plugin install https://github.com/Automattic/newspack-ads/releases/download/v1.4.1/newspack-ads.zip
Downloading installation package from https://github.com/Automattic/newspack-ads/releases/download/v1.4.1/newspack-ads.zip...
Unpacking the package...
Installing the plugin...
Warning: Destination folder already exists. "/Users/danielbachhuber/projects/vanilla/wp-content/plugins/newspack-ads/"
Plugin installation failed.
Warning: The 'https://github.com/Automattic/newspack-ads/releases/download/v1.4.1/newspack-ads.zip' plugin could not be found.
Error: No plugins installed.
```

Does it still reproduce on your end?

**Comment by adekbadek** [comment]
Confirmed, the bug is not reproducible anymore.
