### ISSUE TITLE
Alias remove with delete command

### ISSUE THREAD

**Issue by dingo-d** [wp-cli/extension-command#248]
## Feature Request

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

Every time I go and delete the default plugins or some themes using `wp theme/plugin delete` I first do `wp theme/plugin remove`, and I get reminded in the output

```bash
Did you mean 'delete'?
```

**Describe the solution you'd like**

Symfony console commands are 'smart' to recognize typos, or a similar command (not sure how they do that, but it's neat). It would be cool to have `remove` as an alias to `delete` so both would work.

These are the two that come to mind because I use them on a weekly basis.

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @dingo-d 

`delete` is a specific term in WordPress. Given WordPress offers the suggested command when you run `wp plugin remove`, I don't think we should introduce new terms that aren't present in the UI.

**Comment by dingo-d** [comment]
Would it be possible to then run the command if the suggestion appears? 

> Did you mean 'delete'? [Y]

Then you'd press Y and it would delete the plugin?

**Comment by danielbachhuber** [comment]
@dingo-d I don't have a strong opinion one way or the other. I think there was some issue open to that effect in https://github.com/wp-cli/wp-cli/issues but I can't find it. If you'd like to open a new one with your proposal, we can have some discussion about it.

**Comment by dingo-d** [comment]
Opened up a discussion not to spam the issues board: https://github.com/orgs/wp-cli/discussions/5813 👍🏼
