### ISSUE TITLE
[has-patch] Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by kkmuffme** [wp-cli/extension-command#249]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

`PHP Error: Trying to access array offset on value of type null`
from line 472 & 473 in /src/Theme_Command.php

when running command:
`wp theme update --all` in a PHP 7.4 environment

**Provide a possible solution**

This is bc the default value of line 466 is null instead of an array(), which causes this error in PHP 7.4

`$update_info = ( isset( $all_update_info->response[ $theme->get_stylesheet() ] ) && null !== $all_update_info->response[ $theme->get_stylesheet() ] ) ? (array) $all_update_info->response[ $theme->get_stylesheet() ] : null;`

Change `: null;` to `: array();` to fix this.

**Comment by kkmuffme** [comment]
Same issue also in /src/Plugin_Command.php line 650:

`$update_info     = ( isset( $all_update_info->response[ $file ] ) && null !== $all_update_info->response[ $file ] ) ? (array) $all_update_info->response[ $file ] : null;`

should be `: array();`

=> this was reported in https://github.com/wp-cli/extension-command/issues/237 already (without patch though)

**Comment by kkmuffme** [comment]
@schlessera could you apply this fix? (since pull request for this small thing is more work than necessary for this minor fix)

**Comment by danielbachhuber** [comment]
Assuming this has since been fixed up. Feel free to stop by the `#cli` channel on [WordPress.org Slack](https://make.wordpress.org/chat/) if you'd like help debugging further.
