### ISSUE TITLE
Enable Auto-Updates for plugins via wp-cli

### ISSUE THREAD

**Issue by alexnl** [wp-cli/extension-command#250]
Since WP 5.5 now allows for enabling auto-update for individual plugins, can this functionality be toggled via WP-CLI? Ideally disable or enable, both for a specific plugin as well as for all plugins.

**Comment by leymannx** [comment]
As far as I can see auto-updates enable/disable has not been implemented, yet. Would be a really useful improvement. +1

**Comment by BreezeMaxWeb-NS** [comment]
+1, also, #255 is basically a duplicate of this but it mentions themes as well, not just plugins.

**Comment by jsilvermist** [comment]
I wrote a script to use for this until it's officially added to the wp-cli.

https://gist.github.com/jsilvermist/254598098aac4e8f8afd5d8be446a437

**Comment by schlessera** [comment]
Fixed via #259
