### ISSUE TITLE
Function compatibility UpgraderSkin

### ISSUE THREAD

**Issue by kgfeuerherm** [wp-cli/extension-command#254]
- [ X] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [ X] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports]

**Describe the current, buggy behavior**

After a long period of not using WP CLI, did a wp cli update, which apparently succeeded, then proceeded to instal plug-ins on a new WP multisite.

So far as I can see, the plug-ins do get installed, however, I see the following warning each time:

_Warning: Declaration of WP_CLI\UpgraderSkin::feedback($string) should be compatible with WP_Upgrader_Skin::feedback($string, ...$args) in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/UpgraderSkin.php on line 59_

Note that PHP 7.3 is being forced as in the following example:

```
/opt/cpanel/ea-php73/root/usr/bin/php /usr/local/bin/wp plugin install ns-cloner-site-copier --activate
```

(There was a reason I had to do this as of last year, but I don't remember the details.)

**Let us know what environment you are running this on**

```
/opt/cpanel/ea-php73/root/usr/bin/php /usr/local/bin/wp cli info
OS:	Linux 3.10.0-693.11.6.1.ELK.el6.x86_64 #1 SMP Tue Jan 23 10:30:30 MST 2018 x86_64
Shell:	/usr/local/cpanel/bin/jailshell
PHP binary:	/opt/cpanel/ea-php73/root/usr/bin/php
PHP version:	7.3.21
php.ini used:	/opt/cpanel/ea-php73/root/etc/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/home2/wludh/public_html/2020
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	2.0.0

stat /usr/local/bin/wp
  File: `/usr/local/bin/wp'
  Size: 4668571   	Blocks: 9128       IO Block: 4096   regular file
Device: 851h/2129d	Inode: 2144626     Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-08-28 20:15:28.935285373 -0500
Modify: 2018-08-10 13:18:01.000000000 -0500
Change: 2018-08-14 15:53:58.558452013 -0500
```

**Comment by wojsmol** [comment]
Hi @kgfeuerherm 
Please update WP-CLI to version 2.4.0. In 2.4.0 there are simular issus related  to WordPress 5.5 changes witch will be fixed in next WP-CLI release.

**Comment by kgfeuerherm** [comment]
Ah, I see. My local WP-CLI is 2.4.0, but the server is at 2.0.0. I will have to post a ticket for that, I guess.
