### ISSUE TITLE
Command `wp plugin update --all` freezes when wp installation has plugin with version higher then in official repo

### ISSUE THREAD

**Issue by jasomdotnet** [wp-cli/extension-command#256]
Issue is described [here](https://github.com/wp-cli/extension-command/issues/187) and it is marked as fixed despite issue is still present in `2.4.0` version. See my [comment](https://github.com/wp-cli/extension-command/issues/187#issuecomment-684562957):

> _In August 2020 I updated to `wp-cli 2.4.0` and issue described here appeared. When I rolled back to `2.3.0` problem with `wp plugin update --all` freezing is gone._

Can you reopen that issue #187?

Also see this feature request: #242

**Comment by danielbachhuber** [comment]
@jasomdotnet Is this still an issue?

**Comment by danielbachhuber** [comment]
Actually, looks like this was fixed in https://github.com/wp-cli/extension-command/pull/338
