### ISSUE TITLE
plugin update behavior different when run as part of a bash script

### ISSUE THREAD

**Issue by kkmuffme** [wp-cli/extension-command#262]
I'm using https://github.com/woocommerce/woocommerce-beta-tester with the "Beta" release channel.
When I use:

`wp plugin update woocommerce`

in the command line manually it correctly updates to the RC/Beta of woocommerce.

When I put the same command in a bash (.sh) file however, it always says:
`Success: Plugin already updated.`

I know this sounds weird, could anybody please try if you are able to reproduce this behavior?

WP CLI version: WP-CLI 2.5.0-alpha-9061b3e
WP: 5.5

**Comment by danielbachhuber** [comment]
Hey there,

Hope you were able to figure this out! Feel free to stop by the `#cli` channel on [WordPress.org Slack](https://make.wordpress.org/chat/) if you'd like help debugging further.
