### ISSUE TITLE
Add wp plugin disable as a synonym of wp plugin deactivate

### ISSUE THREAD

**Issue by paulschreiber** [wp-cli/extension-command#267]
## Feature Request
Add `wp plugin disable` as a synonym of `wp plugin deactivate`

- [X] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @paulschreiber

`deactivate` is a specific term in WordPress, while `disable` is somewhat ambiguous. I don't think they're quite as interchangeable as `upgrade` and `update.
