### ISSUE TITLE
Pathological plugin makes `plugin list` inconsistent with `plugin verify-checksums`

### ISSUE THREAD

**Issue by kitchin** [wp-cli/extension-command#268]
See: https://wordpress.org/support/topic/cannot-update-powerpress-plugin/
The plugin Powerpress mistakenly put plugin headers in two php files, `powerpress.php` and `powerpress-network.php`. 

Arguably `wp-cli` should handle this better.  WP Dashboard handles it by listing both plugins in `wp-admin/plugins.php` and allowing an update, at least on the first one. The developer fixed the plugin and clicking update resolves the problem.

In `wp-cli` we get an inconsistent listing when running `plugin verify-checksums` after `plugin list`. Should probably show an error or warning on `plugin list`. Current behavior mixes up the path-based name of the plugin.

`plugin list` output:
>powerpress/powerpress,active,available,8.4
>powerpress/powerpress-network,inactive,available,1.0.1

`plugin verify-checksums` output:
>Warning: Could not retrieve the checksums for version 8.4 of plugin powerpress, skipping.
>Warning: Could not retrieve the checksums for version 8.4 of plugin powerpress, skipping.

**Comment by danielbachhuber** [comment]
@kitchin Is this still an issue?
