### ISSUE TITLE
Update private plugin url

### ISSUE THREAD

**Issue by cedriclajato** [wp-cli/extension-command#271]
How to update private plugin using url if its not available on WP repository since it's private.

**Comment by schlessera** [comment]
GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review HTTP://wp-cli.org/#support

The easiest way to get support is to join us in the #cli channel on the [Make WordPress Slack Team](https://make.wordpress.org/chat/).
