### ISSUE TITLE
PHP 8

### ISSUE THREAD

**Issue by RoundAboutWEB** [wp-cli/extension-command#272]
When will wp-cli be compatible with PHP 8?

**Comment by schlessera** [comment]
It should be compatible with PHP 8 in its latest dev version. However, recently Travis CI just stopped supporting Open Source projects, and it was also used to build the latest nightly.

I'm currently migrating everything to GitHub Actions. Once that is done, we should have a nightly compatible with PHP 8 and then I'll push a new release.
