### ISSUE TITLE
wp plugin update plugin with downgraded version cannot be updated anymore

### ISSUE THREAD

**Issue by SantinoPetrovic** [wp-cli/extension-command#282]
I am using wp-smushit as an example. 

I run this command: `wp plugin list --path=/var/www/site/wordpress/`

I get this output:

+-------------------------------------+----------+--------+---------+
| name                                | status   | update | version |
+-------------------------------------+----------+--------+---------+
| wp-smushit                          | active   | none   | 3.8.3   |
+-------------------------------------+----------+--------+---------+

I tried to downgrade wp-smushit from 3.8.3 to 3.8.2 with `wp plugin install wp-smushit --version=3.8.2 path=/var/www/site/wordpress/` and downgraded output is:

`Downloading installation package from https://downloads.wordpress.org/plugin/wp-smushit.3.8.2.zip...
Unpacking the package...
Installing the plugin...
Removing the old version of the plugin...
Plugin updated successfully.
Success: Installed 1 of 1 plugins.
`

However, if I check it again with `wp plugin list --path=/var/www/site/wordpress/` , I get this output:

+-------------------------------------+----------+--------+---------+
| name                                | status   | update | version |
+-------------------------------------+----------+--------+---------+
| wp-smushit                          | active   | none   | 3.8.2   |
+-------------------------------------+----------+--------+---------+

The version is right, but the plugin is not updatable anymore. I tried to update the plugin with `wp plugin update wp-smushit  --path=/var/www/site/wordpress/`, but I only get this output with no changes:

`Success: Plugin already updated.`

Is it a bug or is it something I'm doing wrong?

**Comment by danielbachhuber** [comment]
Thanks for the report, @SantinoPetrovic !

Your update check probably has a stale cache. Feel free to stop by the `#cli` channel on [WordPress.org Slack](https://make.wordpress.org/chat/) if you'd like help debugging further.
