### ISSUE TITLE
wp update with --patch  option does not update a plugin with a patch version change

### ISSUE THREAD

**Issue by theghall** [wp-cli/extension-command#296]
## Bug Report

--- ✅ If you are in the correct location now... --->

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

wp plugin update <plugin> --patch does not update a plugin with a patch version change

```
> wp plugin update --all --dry-run
Available plugin updates:
+---------------+--------+---------+----------------+
| name          | status | version | update_version |
+---------------+--------+---------+----------------+
| sg-cachepress | active | 5.9.4   | 5.9.5          |
+---------------+--------+---------+----------------+
> wp plugin update sg-cachepress --patch --dry-run
No plugin updates available.


**Describe how other contributors can replicate this bug**

- Make a patch to a plugin
- run `wp plugin update <plugin> --patch`

**Describe what you would expect as the correct outcome**

A plugin with a patch version should update

**Let us know what environment you are running this on**

```
OS:	Linux 3.12.18-clouder0 #6 SMP PREEMPT Mon Apr 12 16:04:39 EEST 2021 x86_64
Shell:	/bin/bash
PHP binary:	/usr/local/php74/bin/php-cli
PHP version:	7.4.22
php.ini used:	/usr/local/php74/lib/php.ini
MySQL binary:	/bin/mysql
MySQL version:	mysql  Ver 15.1 Distrib 10.3.27-MariaDB, for Linux (x86_64) using readline 5.1
SQL modes:	
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/home/customer/www/jennystampsup.com/public_html
WP-CLI packages dir:	/home/** ssh username redacted **/.wp-cli/packages/
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	2.5.0
```

**Provide a possible solution**

If you happen to have a suggestion on how to fix this bug, please tell us in here.

Just leave this section out if you don't know how to fix it.

**Provide additional context/Screenshots**

Add any other context about the problem here.

If applicable, add screenshots to help explain (you can just drag&drop images into the Github issue).

**Comment by Sidsector9** [comment]
@theghall for me this is working on WP-CLI 2.6.0, can you update your version and try it again?


<img width="1049" alt="Screen Shot 2022-06-07 at 9 35 07 AM" src="https://user-images.githubusercontent.com/17757960/172293670-6afeb660-f5cd-4c31-8005-714332ae9986.png">

**Comment by theghall** [comment]
@[Sidsector9](https://github.com/Sidsector9) Looks like my host updated the version.  I'll give it a go
