### ISSUE TITLE
Use --minor to limit plugin and theme updates to minor releases

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/extension-command#3]
As a WordPress developer, I may want to only update a plugin or theme to its latest minor release.

For instance, if I'm running WooCommerce 2.9.1, and the plugin author releases 2.9.2 and 3.0.2, I may only want to update to 2.9.2.

Previously https://github.com/wp-cli/wp-cli/issues/3974

**Comment by schlessera** [comment]
This probably needs some discussion as to what we consider "minor", as WordPress plugins generally don't use SemVer.

So, 3.0 -> 3.1, is that minor?
Do we consider everything that is not the left-most number to be minor?
Or do we differentiate between version numbers with 2 components and version numbers with 3 components?

**Comment by danielbachhuber** [comment]
We could also follow SemVer, offer `--minor` and `--patch`, and leave it up to the end user to decide which flag they need to use to update a given plugin.

**Comment by schlessera** [comment]
Yes, probably a good idea. We can give feedback in the lines of `Found 'minor' update. Not updating, only 'patch'-level updates allowed.`

**Comment by danielbachhuber** [comment]
As it turns out, this is only possible for plugins because WordPress.org doesn't provide a version list for themes.
