### ISSUE TITLE
Suggestion: use 'all_plugins' filter in all commands that affect all plugins 

### ISSUE THREAD

**Issue by goldenapples** [wp-cli/extension-command#30]
I noticed that the `wp plugin` cli command doesn't make use of the `all_plugins` filter which is used in the WP_Plugins_List_Table controller. This filter can be used in the dashboard to modify the list of plugins which are visible in the plugins list table, among other things. For example, I'm using it in a project to hide a dev-only plugin from production environments.

This means that the list of plugins available through `wp plugin list` is different from that shown on `wp-admin/plugins.php`. Also, other inconsistencies exist - the biggest I've come across being that `wp plugin activate --all` may activate different plugins than the "Activate" bulk action on the plugins page.   

I think that it would be good for all the `wp plugin` subcommands to wrap any `get_plugins()` calls with this filter. I'm happy to make a PR for it, but wanted to get a second opinion before jumping in with it.

**Comment by danielbachhuber** [comment]
> I think that it would be good for all the wp plugin subcommands to wrap any get_plugins() calls with this filter.

👍 Seems reasonable to me.
