### ISSUE TITLE
Updating any plugin always fails

### ISSUE THREAD

**Issue by jean-christophe-manciot** [wp-cli/extension-command#317]
I have encountered a fatal issue with elementor pro which prevents any page below ```wp-admin/``` from loading correctly which makes plugin updating impossible from wp-admin.
I tried to update the plugins using wp cli, but there is also an issue!

```
$ wp --info
OS:	Linux 5.15.0-28-generic #29-Ubuntu SMP Wed Apr 27 12:58:00 UTC 2022 x86_64
Shell:	/bin/bash
PHP binary:	/usr/bin/php8.1
PHP version:	8.1.5
php.ini used:	/etc/php/8.1/cli/php.ini
MySQL binary:	/usr/bin/mysql
MySQL version:	mysql  Ver 8.0.28-0ubuntu4 for Linux on x86_64 ((Ubuntu))
SQL modes:	ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/media/SAMSUNG9-Shared/srv/https
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	2.6.0
```

```
$ wp plugin update elementor
Enabling Maintenance mode...
Downloading update from http://downloads.wordpress.org/plugin/elementor.3.6.5.zip...
Warning: Download failed. "cURL error 77: "
Disabling Maintenance mode...
+-----------+-------------+-------------+--------+
| name      | old_version | new_version | status |
+-----------+-------------+-------------+--------+
| elementor | 3.5.0       | 3.6.5       | Error  |
+-----------+-------------+-------------+--------+
Error: No plugins updated.
```
We can notice that it tries to download from **http** instead of **https**. I don't know how to change that behavior.

Any suggestion for a workaround?

**Comment by danielbachhuber** [comment]
Hey @jean-christophe-manciot,

Thanks for the report!

If some plugin is interfering with the operation of WP-CLI, you can use the `--skip-plugins` flag to skip all or a specific plugin from loading.

Here's a bit more detail on how it works: https://make.wordpress.org/cli/handbook/guides/identify-plugin-theme-conflict/

Hope this helps!

**Comment by jean-christophe-manciot** [comment]
@danielbachhuber 
It seems that you have not read this report carefully, including this part: **it tries to download from http instead of https**. This is why all plugin updates fail and so this does not depend any plugin, all plugins are affected by this issue.
