### ISSUE TITLE
wp plugin download

### ISSUE THREAD

**Issue by dnavarrojr** [wp-cli/extension-command#33]
Would really like to see

`wp plugin download`

For downloading the ZIP file of plugins without installing them.  This would allow me auto-download updates for archival, which I am pretty much doing by hand.

Obviously it would only work with plugins that support updates through the dashboard.

By default it would not override an existing file unless the downloaded version is newer.  With an option for "--override" to force a download anyway.  And a "--path=" would be nice as well.

**Comment by schlessera** [comment]
Thanks for the feature request.

However, this has recently been discussed here: https://github.com/wp-cli/extension-command/issues/26

Downloading a plugin ZIP file can simply be done through `wget`, so there's no point in providing an additional WP-CLI command for this.
