### ISSUE TITLE
 Plugin already installed/active should be notice rather than warnings

### ISSUE THREAD

**Issue by drzraf** [wp-cli/extension-command#34]
`$ wp plugin install wordpress-importer --activate`

>       Activating 'wordpress-importer'...
>       Success: Plugin already installed.
>
>       Warning: wordpress-importer: Plugin already installed.
>       Warning: Plugin 'wordpress-importer' is already active.

Warning is not correct. The WP installation is in the state we expected to find it (although our requested operation wasn't needed). If double installation/activation *intent* do not hurt [eg no double-execution of install() function], then it should not be treated as a warning, but simply a notice.

**Comment by danielbachhuber** [comment]
Hi @drzraf,

Thanks for the suggestion. This is long-standing behavior that we're unlikely to change.
