### ISSUE TITLE
Plugin from GitHub renamed incorrectly.

### ISSUE THREAD

**Issue by dseomn** [wp-cli/extension-command#35]
I tried to install a plugin from a tag archive on GitHub, and wp-cli renamed it from `dseomn-customizations-wp-0.0.2` to `dseomn-customizations-w` instead of `dseomn-customizations-wp`.

```
$ wp plugin install https://github.com/dseomn/dseomn-customizations-wp/archive/v0.0.2.zip 
Downloading install package from https://github.com/dseomn/dseomn-customizations-wp/archive/v0.0.2.zip...
Unpacking the package...
Installing the plugin...
Renamed Github-based project from 'dseomn-customizations-wp-0.0.2' to 'dseomn-customizations-w'.
Plugin installed successfully.
Success: Installed 1 of 1 plugins.
```

**Comment by schlessera** [comment]
A quick glance at the code lets me think that WP-CLI has tried to remove the tag `v0.0.2` (note the `v`) from the folder name, but the folder only had `0.0.2` as a tag, so it removed one additional letter from the name itself.

Did you at one point change the name of your tags in your repository?

**Comment by dseomn** [comment]
> Did you at one point change the name of your tags in your repository?

Nope. I think it's standard to strip the leading v from a tag name when generating an archive, but I'm not sure.

**Comment by danielbachhuber** [comment]
🔨
