### ISSUE TITLE
Optional field for plugin author

### ISSUE THREAD

**Issue by bgoewert** [wp-cli/extension-command#368]
## Feature Request

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

It would be helpful to have an option to list the plugin author. For an example, an agency is asking for a list of plugins on one of the sites I maintain. I thought that I'd try using wp-cli to quickly get a CSV of all the active plugins. However, several plugins that were created internally and do not have great names or descriptions, but the author was set as a unique internal name. Without the author listed, I still have to go through the list and define which ones were created internally.

Edit: Updated use case. I wrote a sloppy original description because I was in a hurry.

**Describe the solution you'd like**

Add an optional field to list the plugin author.

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @bgoewert ! This seems like a reasonable request.

Feel free to submit a pull request, if you'd like. Here is some [guidance on our pull request best practices](https://make.wordpress.org/cli/handbook/contributions/pull-requests/).

**Comment by toddr** [comment]
This should have been resolved by #639, correct?

**Comment by schlessera** [comment]
Fixed via #369
