### ISSUE TITLE
Theme switch with 'theme activate' cause error

### ISSUE THREAD

**Issue by holmberd** [wp-cli/extension-command#40]
## Summary

After installing theme `JointsWP version: 4.0` and trying to activate it, I recive `Error: Could not switch to 'JointsWP - Sass' theme`, but looking at `wp themes list` shows me that the theme was activated.

Default theme `twentysixteen version 1.3`

Added my own code solution at the bottom.

## Steps to reproduce
`wp --path={wordpress-path} theme install https://github.com/JeremyEnglert/JointsWP/archive/4.0.zip --force --activate`

or 

`wp --path={wordpress-path} theme activate JointsWP`

### System
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

### PHP
```
/usr/bin/php
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
```

### WP
```
$wp_version = '4.8.1';

File: '/usr/local/bin/wp'
Size: 4292472   	Blocks: 8384       IO Block: 4096   regular file
Device: ca01h/51713d	Inode: 22471       Links: 1
Access: (0755/-rwxr-xr-x)  Uid: ( 1000/  ubuntu)   Gid: (    0/    root)
Access: 2017-09-06 16:50:57.249169145 +0000
Modify: 2017-09-06 16:41:20.037346058 +0000
Change: 2017-09-06 16:50:56.433175137 +0000
 Birth: -
```

## Results and impacts
- Severity – High
- Expected Results: Switch between themes without error message.
- Actual Results: `Error: Could not switch to 'JointsWP - Sass' theme` is displayed.
- This causes a problem when installing and switching to a new theme when running Ansible playbooks.

## Relevant diagnostics

https://gist.github.com/holmberd/036b1a4a983e17c5c508335a293e900d

## Suggestions

Could it be a asynchronous problem where the conditional check to see if the theme is active fires too early? Since [switch_theme ](https://developer.wordpress.org/reference/functions/switch_theme/) provides a hook, see code below. It would make sense to use that as a callback for the `do_action`.

https://github.com/wp-cli/extension-command/blob/e000763bc05e61fdb5fea51dfcf82150d0918181/src/Theme_Command.php#L223

```
// File: wp-includes/theme.php

 /**
     * Fires after the theme is switched.
     *
     * @since 1.5.0
     * @since 4.5.0 Introduced the `$old_theme` parameter.
     *
     * @param string   $new_name  Name of the new theme.
     * @param WP_Theme $new_theme WP_Theme instance of the new theme.
     * @param WP_Theme $old_theme WP_Theme instance of the old theme.
     */
    do_action( 'switch_theme', $new_name, $new_theme, $old_theme );
```

### Code Suggestion
```
// File: extension-command/src/Theme_Command.php

function is_theme_active($new_name, $new_theme, $old_theme) {
	if ( $this->is_active_theme( $new_theme ) ) {
	    WP_CLI::success( "Switched to '$new_name' theme." );
  	} else {
  	    WP_CLI::error( "Could not switch to '$new_name' theme." );
  	}
  }

  add_action( 'switch_theme', 'is_theme_active', 10, 3 );
  switch_theme( $theme->get_template(), $theme->get_stylesheet() );

```

**Comment by miya0001** [comment]
I couldn't reproduce this problem.
I can see theme as expected.

I guess there is reverse proxy or cache plugin or so.

```
$ wp theme install https://github.com/JeremyEnglert/JointsWP/archive/4.0.zip --force --activate
Downloading install package from https://github.com/JeremyEnglert/JointsWP/archive/4.0.zip...
Unpacking the package...
Installing the theme...
Renamed Github-based project from 'JointsWP-4.0' to 'JointsWP'.
Removing the old version of the theme...
Theme updated successfully.
Activating 'JointsWP'...
Success: Switched to 'JointsWP - Sass' theme.
Success: Installed 1 of 1 themes.
```

```
$ wp --info
PHP binary:	/usr/bin/php7.0
PHP version:	7.0.22-0ubuntu0.16.04.1
php.ini used:	/etc/php/7.0/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/home/vagrant
WP-CLI packages dir:	
WP-CLI global config:	/home/vagrant/.wp-cli/config.yml
WP-CLI project config:	
WP-CLI version:	1.3.0
```

I guess it is a problem with your environment/install.

Github issues aren't for general support questions, but there are other venues you can try: http://wp-cli.org/#support Make sure you're running the most recent version of WP-CLI! The current version is the only officially supported version.

Thanks

**Comment by holmberd** [comment]
@miya0001 from your answer I assume you read nothing of what I actually wrote, amazing.

## Additional Information

- To be extra specific, this is a fresh install of ubuntu, nothing else is running on this machine. 

- I'm running the **latest version** of **WP-CLI** with `curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar`

- Download wordpress core with `wp core download`

- Install wordpress `wp core install --url=.. --title=..`

- Install plugins with `wp plugin install plugin-item --force --activate`
  - with plugins:
     - 'advanced-custom-fields'
     - 'akismet'
     - 'amazon-web-services'
     - 'duplicate-post'
     - 'wordpress-importer'
     - 'amazon-s3-and-cloudfront'

- Then fetch and install the wordpress theme as mentioned in the previous post.

I will see if installing the plugins after trying to activate the theme makes any difference, but I feel this behaviour should work.

**Comment by miya0001** [comment]
Hi @holmberd 

Can you share command example to reproduce your problem?
I tried following on Ubuntu 16.04.

```
$ wp core download
$ wp config create \
--dbhost=localhost \
--dbname=wp \
--dbuser=root \
--dbpass=wordpress \
--dbprefix=wp_ 
$ wp db create
$ wp core install \
--url=http://127.0.0.1:8080 \
--title="WordPress" \
--admin_user="admin" \
--admin_password="admin" \
--admin_email="admin@example.com"
$ wp theme install https://github.com/JeremyEnglert/JointsWP/archive/4.0.zip \
--force --activate
```

The last output:

```
Unpacking the package...
Installing the theme...
Renamed Github-based project from 'JointsWP-4.0' to 'JointsWP'.
Removing the old version of the theme...
Theme updated successfully.
Activating 'JointsWP'...
Success: Switched to 'JointsWP - Sass' theme.
Success: Installed 1 of 1 themes.
```
