### ISSUE TITLE
Add "--exec=<php-code>" argument to "plugin" command

### ISSUE THREAD

**Issue by jcvignoli** [wp-cli/extension-command#405]
It may be useful to use the argument
`--exec=<php-code>`
when executing
`wp plugin whatever`

If using on the same local dev two different databases, one can't access both. But sending for example a
`define( 'FIRST_DB', true )`
would allow to switch from one db to the second.

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @jcvignoli !

This is achievable with a little bit of custom code:

```
$ cat hook.php
<?php
WP_CLI::add_hook(
	'before_run_command',
	function( $command ) {
		$base = array_shift( $command ); 
		if ( 'plugin' === $base ) {
			WP_CLI::log( 'You ran the plugin command!' );
		}
	}
);
$ wp --require=hook.php plugin status hello
You ran the plugin command!
Plugin hello details:
    Name: Hello Dolly
    Status: Inactive
    Version: 1.7.2
    Author: Matt Mullenweg
$ wp --require=hook.php theme status twentytwentyfour
Theme twentytwentyfour details:
    Name: Twenty Twenty-Four
    Status: Inactive
    Version: 1.0
    Author: the WordPress team
```

**Comment by jcvignoli** [comment]
Thanks. But I run some tests with your solution; with some wp commands like "config list", it works.
With cron event run --due-now, it doesn't.

**Comment by jcvignoli** [comment]
@danielbachhuber, this doesn't work.
I tried the following code:
```
WP_CLI::add_hook(
	'before_run_command',
	function( $command ) {
		define('MY_CONST_THAT_CHANGE_DB', true);
		WP_CLI::log( 'You ran the plugin command!' );
	}
);
```
A `wp config list` (with the --require) shows me it swittched to the correct database. However, a `wp cron run event --due-now` sticks to the default database, the one that is selected if the constant is not found.
The constant is not passed when using this method.

**Comment by danielbachhuber** [comment]
> However, a `wp cron run event --due-now` sticks to the default database, the one that is selected if the constant is not found.
> The constant is not passed when using this method.

@jcvignoli Is the constant already defined?

**Comment by jcvignoli** [comment]
@danielbachhuber could you reopen this very issue? Until a solution is found, there is no way afaik to pass a constant with a cron.

**Comment by danielbachhuber** [comment]
> Until a solution is found, there is no way afaik to pass a constant with a cron.

This is a support request though, not a bug with WP-CLI. The `#cli` channel on [WordPress.org Slack](https://make.wordpress.org/chat/) is a good place to ask support questions.

I think, but I'm not positive, that cron might be spawning a HTTP request. If you `define( 'DISABLE_WP_CRON', true );`, you can run cron entirely with WP-CLI.
