### ISSUE TITLE
Block passing --activate in theme install with multiple themes

### ISSUE THREAD

**Issue by ernilambar** [wp-cli/extension-command#406]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

When two themes are passed to install with activate flag, first theme is activated and after second theme is installed, newly installed theme is activated.

`wp theme install simple-life blue-planet --activate`

May be we should warn users in such case like: 

``` 
Error: Only a single theme can be active.
```
 
**Describe what you would expect as the correct outcome**

`Error: Only a single theme can be active.`

**Comment by danielbachhuber** [comment]
Good catch!

Another option is a warning instead of an error. I think I'd opt for the warning because throwing an error would be a breaking change.
