### ISSUE TITLE
[ wp theme update ] - update from zip file ( like install )

### ISSUE THREAD

**Issue by riccardodicurti** [wp-cli/extension-command#409]
I saw that it is possible to install a theme from a zip file but cannot update it. 

`wp theme install http://s3.amazonaws.com/bucketname/my-theme.zip?AWSAccessKeyId=123&Expires=456&Signature=abcdef`

I would like to ask if it would be possible to add this feature, the themes I need to update I have them as zip file and they are not available in repository, also being active or parent themes I cannot delete to install them again.

**Comment by danielbachhuber** [comment]
Thanks for the report, @riccardodicurti

`wp theme update` uses the WordPress updater, so`wp theme install` is the most appropriate command to forcefully install a ZIP
