### ISSUE TITLE
`wp plugin status wp-redis` Couldn't find plugin-status.mustache

### ISSUE THREAD

**Issue by szepeviktor** [wp-cli/extension-command#433]
## Bug Report

- [ ] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [ ] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

WP-CLI 2.10.0

```
$ wp plugin status wp-redis
Error: Couldn't find plugin-status.mustache
```

https://github.com/wp-cli/extension-command/blob/2a6f985a303032cd3ee0f37bfbf8e08420fa47ae/src/Plugin_Command.php#L227

**Describe what you would expect as the correct outcome**

No error.

**Comment by szepeviktor** [comment]
same for 

https://github.com/wp-cli/extension-command/blob/2a6f985a303032cd3ee0f37bfbf8e08420fa47ae/src/Theme_Command.php#L186

**Comment by swissspidy** [comment]
I believe we're tracking this in https://github.com/wp-cli/wp-cli/issues/5907 already

The latest update is [this one](https://github.com/wp-cli/wp-cli-bundle/pull/649#issuecomment-2274319640) from @schlessera:

> I don't think this approach is ideal. It is still very hacky and it has issues with multibyte strings in filesystems.
> 
> I think this needs to be solved using [php.net/manual/en/phar.running.php](https://www.php.net/manual/en/phar.running.php) in the correct way. I'll have a stab at it...

**Comment by szepeviktor** [comment]
Thank you, Pascal.
