### ISSUE TITLE
`wp plugin` command isn't working with WordPress 3.7 - 3.9

### ISSUE THREAD

**Issue by miya0001** [wp-cli/extension-command#46]
It can't detect updates are available on WordPress 3.7 - 3.9.

Related:
https://github.com/wp-cli/wp-cli/issues/4376

**Comment by gitlost** [comment]
It looks as if php-curl isn't installed by default in the new Travis stuff so the response code is a string and failing this strict inequality https://github.com/wp-cli/extension-command/blob/master/src/WP_CLI/CommandWithUpgrade.php#L253. This was only catered for in WP 4.1 https://core.trac.wordpress.org/ticket/28887.

**Comment by miya0001** [comment]
@gitlost Oh, thanks. I'll try it.

**Comment by miya0001** [comment]
@gitlost 

Unfortunately, the problem wasn't solved, because this function is called at only installing.
I guess update information is saved into transient API and it is saved by WordPress core.(?)
I will look into more details.

But I agree that we need to fix the strict inequality.
https://github.com/WordPress/WordPress/blob/3.7.22/wp-includes/http.php#L248-L263

I will open a new issue as `good-first-issue`. :)

**Comment by gitlost** [comment]
Oh I see, the tests are failing for me too locally (with curl enabled) for WP 3.9.20 but working for WP 4.0. Odd.

**Comment by danielbachhuber** [comment]
@miya0001 What needs to be done to resolve this issue?

**Comment by miya0001** [comment]
I haven't look into details for now yet.
The test was passed at 5 days ago, I am wondering what introduce this problem.

**Comment by miya0001** [comment]
Ah, it is not working on WordPress core too.
I guess this problem was introduced by something changes on WordPress plugins API for last few days.

**Comment by gitlost** [comment]
> Ah, it is not working on WordPress core too.

@miya0001 Could you expand on what you tested here?! :smiley: 

> I guess this problem was introduced by something changes on WordPress plugins API for last few days.

I wonder is there any way of checking if this happened?

I just now found out why it's working on 4.0 and not before, due to this core change https://core.trac.wordpress.org/ticket/17902, but as you say it's very confusing that up to 5 days ago things worked.

I suppose a compatibility workaround would be to pre- and post- filter the `update-checks` http request, though doing this without fully understanding how the breaking change occurred isn't reassuring.

**Comment by miya0001** [comment]
I asked #meta on slack. :)
https://wordpress.slack.com/archives/C02QB8GMM/p1506162916000103

> I guess this problem was introduced by something changes on WordPress plugins API for last few days.
It was my misunderstanding.

We have to install another plugin for those tests. :)
I'll open new PR for it.

Thanks 😊

**Comment by gitlost** [comment]
> I asked #meta on slack

Ah excellent. So I was barking up the wrong tree with https://core.trac.wordpress.org/ticket/17902.

> We have to install another plugin for those tests.

Or maybe tag them as requiring WP 4.0 and introduce other tests for < 4.0.
