### ISSUE TITLE
The response code from plugins API should be checked as a string

### ISSUE THREAD

**Issue by miya0001** [wp-cli/extension-command#47]
The return value of the `wp_remote_retrieve_response_code()` is as a `string`.
https://github.com/WordPress/WordPress/blob/3.7.22/wp-includes/http.php#L248-L263

But following line is checking value as a integer.
https://github.com/wp-cli/extension-command/blob/master/src/WP_CLI/CommandWithUpgrade.php#L253

I want to leave this issue as a `good-first-issue`. :)

**Comment by miya0001** [comment]
Related:
https://github.com/wp-cli/extension-command/issues/46#issuecomment-331389477

**Comment by BhargavBhandari90** [comment]
@miya0001 Can you please tell me in which command this is being used. 

I tried `plugin install` and `plugin update` command. But it seems this is not the part of those commands.

How can I make sure that my changes is correct or not for this issue?

**Comment by miya0001** [comment]
Hi @BhargavBhandari90 :)

Maybe `wp plugin install <slug> --version`.
https://github.com/wp-cli/extension-command/blob/315bc369fd4f5c11165dd554dc8602265de60abf/src/Plugin_Command.php#L474
