### ISSUE TITLE
Tests for wp plugin list --status=dropins are fragile

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/extension-command#57]
The tests for `wp plugin list --status=dropins` added in #18 are fragile because they rely on the third party plugin Query Monitor retaining its dropin plugin, and rely on it automatically putting the dropin into place upon activation.

Instead, the test should create its own dropin file and put that into place.

**Comment by miya0001** [comment]
Ah, I tried the command with empty `db-error.php`.

Then `db-error.php` is in Wordpress admin like following.

![](https://www.evernote.com/l/ABU65GXrJdBDEacCbOq1-mfRxFOblwG-k04B/image.png)

But `wp plugin list --status=dropins` couldn't find `db-error.php`.

```
$ wp plugin list --status=dropins
+------+--------+--------+---------+
| name | status | update | version |
+------+--------+--------+---------+
+------+--------+--------+---------+
```

I'll send PR to fix this problem and test issue.

**Comment by miya0001** [comment]
Ah, option should be `--status=dropin`.
OK, I'll update only tests. 😊
