### ISSUE TITLE
Add last_updated to wp plugin list's optional arguments

### ISSUE THREAD

**Issue by pwtyler** [wp-cli/extension-command#59]
I have a couple cases where I want to check how recently an update was released before running `wp plugin update`. Right now I use cUrl and the .org plugin API where it is readily available, but would love to do this directly from wp-cli if possible.

The date can be found at `https://api.wordpress.org/plugins/info/1.0/<PLUGIN-SLUG>.json`, but I do not know if it is available through the native WordPress functions.

**Comment by danielbachhuber** [comment]
> I do not know if it is available through the native WordPress functions.

It looks like it isn't stored in the `update_plugins` transient:

```
wp option get _site_transient_update_plugins
stdClass::__set_state(array(
   'last_checked' => 1502730412,
   'response' =>
  array (
    'akismet/akismet.php' =>
    stdClass::__set_state(array(
       'id' => 'w.org/plugins/akismet',
       'slug' => 'akismet',
       'plugin' => 'akismet/akismet.php',
       'new_version' => '3.3.4',
       'url' => 'https://wordpress.org/plugins/akismet/',
       'package' => 'https://downloads.wordpress.org/plugin/akismet.3.3.4.zip',
       'tested' => '4.8.1',
       'compatibility' =>
      stdClass::__set_state(array(
      )),
    )),
  ),
```

WP-CLI uses `wp_update_plugins()` to refresh the transient, as core does. This function calls `http://api.wordpress.org/plugins/update-check/1.1/`, which doesn't appear to return the `last_updated` data.

Conceivably, we could open a Meta Trac ticket about including this data in the API response, and then accommodate for it in WP-CLI.

**Comment by danielbachhuber** [comment]
> Conceivably, we could open a Meta Trac ticket about including this data in the API response, and then accommodate for it in WP-CLI.

Opened a Meta Trac ticket: https://meta.trac.wordpress.org/ticket/3222

**Comment by danielbachhuber** [comment]
Hi @pwtyler,

Thanks again for opening the issue. At this point, the decision is that this isn't a compelling enough use case to add the data to the API. We can reconsider in the future if there's a user-facing justification for the data.

**Comment by pwtyler** [comment]
Makes sense, thanks for the followup and looking into it in the first place.
