### ISSUE TITLE
PHP Notice: undefined index 'package'

### ISSUE THREAD

**Issue by markjaquith** [wp-cli/extension-command#64]
I'm getting a PHP Notice:

`PHP Notice:  Undefined index: package in phar:///usr/bin/wp/vendor/wp-cli/extension-command/src/Plugin_Command.php on line 621`

```bash
wp --version
WP-CLI 1.4.0
```

Seems to be from this. Probably some plugin custom filtering the array.

https://github.com/wp-cli/extension-command/blob/64b536e8435fcfdbd4d9351028951b6dcd146b63/src/Plugin_Command.php#L621

**Comment by danielbachhuber** [comment]
Can you [debug to see if there's a conflicting plugin or theme](https://make.wordpress.org/cli/handbook/identify-plugin-theme-conflict/)?
