### ISSUE TITLE
Install/update functionality taken from Core should not be localized

### ISSUE THREAD

**Issue by schlessera** [wp-cli/extension-command#68]
WP-CLI output is not localized because it is meant to be easily parsable.

However, for some commands, like `plugin update`, WordPress functionality is being used that then produces localized output. We should force this WordPress functionality to produce English output that matches the rest of WP-CLI.

Example output (see [Slack discussion](https://wordpress.slack.com/archives/C02RP4T41/p1511862815000169)):
```
$ wp theme update --all

מעבר למצב תחזוקה...
מוריד עדכונים מ-https://downloads.wordpress.org/theme/hueman.3.3.25.zip...
Using cached file '/home/xxx/.wp-cli/cache/theme/hueman-3.3.25.zip'...
פתיחת עדכון...
התקנת גרסה חדשה...
הסרת הגרסה הקודמת של התבנית...
התבנית עודכנה בהצלחה.
ביטול מצב תחזוקה...
+--------+-------------+-------------+---------+
| name   | old_version | new_version | status  |
+--------+-------------+-------------+---------+
| hueman | 3.3.24      | 3.3.25      | Updated |
+--------+-------------+-------------+---------+
Success: Updated 1 of 1 themes.
```

**Comment by schlessera** [comment]
Related https://github.com/wp-cli/wp-cli/issues/4533

**Comment by danielbachhuber** [comment]
> We should force this WordPress functionality to produce English output that matches the rest of WP-CLI.

I'm not convinced forcing English output is the best approach because I'm concerned it may have unintended consequences. If it did have unintended consequences, it probably wouldn't be worth the change.

As an alternative, we could have some documentation that included a code snippet for the user to force this behavior.

**Comment by schlessera** [comment]
Maybe keep the current behavior for BC, but add an optional switch to force English?

**Comment by danielbachhuber** [comment]
> add an optional switch to force English?

Decisions not options?

**Comment by danielbachhuber** [comment]
@rabin-io This code snippet works for me:

Given a `force-locale.php` file:

```
<?php
WP_CLI::add_wp_hook( 'pre_option_WPLANG', function() {
	return 'en_US';
});
```

You can force the locale to `en_US` with:

```
wp --require=force-locale.php
```

The nice thing about this approach is that you can easily apply it across multiple WP installs.

I don't think setting the `WPLANG` constant works if you have the option stored in the database. I haven't tested fully though.

**Comment by rabin-io** [comment]
Thanks @danielbachhuber , I did try it, and it seems to work for me. 
added globally by entering it to the global wp-cli config file `~/.wp-cli/config.yml`

**Comment by danielbachhuber** [comment]
Handling this with documentation https://github.com/wp-cli/handbook/pull/181

**Comment by pandjarov** [comment]
WP-CLI should. honour what's in the ENV not what's the WP config...
