### ISSUE TITLE
Activating already activated plugin gives 2 messages.

### ISSUE THREAD

**Issue by Sidsector9** [wp-cli/extension-command#73]
When activating an already activated plugin, cli gives two messages:

```
wp plugin activate buddypress
Warning: Plugin 'buddypress' is already active.
Success: Plugin already activated.
```

I think we can get rid of the success message.

**Comment by danielbachhuber** [comment]
See https://github.com/wp-cli/wp-cli/issues/3577 for the history

**Comment by schlessera** [comment]
@Sidsector9 These are printed on different devices.
STDERR - `Warning: Plugin 'buddypress' is already active.`
STDOUT - `Success: Plugin already activated.`

As an example, if you redirect STDERR to an error log, you'll still get the result line on the screen:
```
$ wp plugin activate buddypress 2> error-log.txt
Success: Plugin already activated.
```

You'll get 1 warning per issue on STDERR if you activate multiple plugins at once.
But you'll always get 1 single result line on STDOUT.

Both mechanisms are important for scripting purposes.
