### ISSUE TITLE
Plugin install takes wrong name from github URL & renames plugin to 'archive'

### ISSUE THREAD

**Issue by gitlost** [wp-cli/extension-command#80]
Originally from @scarstens, https://github.com/wp-cli/wp-cli/issues/4620

The name of the plugin from a github URL such as `https://github.com/Automattic/sensei/archive/version/1.9.19.zip` is misread as `archive` instead of `sensei`.

See https://github.com/wp-cli/extension-command/blob/v1.1.8/src/WP_CLI/CommandWithUpgrade.php#L159-L162

The fix is easy, add a `$matches` to the `preg_match` and set `$branch_name = $matches[2]`.

**Comment by gitlost** [comment]
Looking properly at this, it all seems very guessy as to what directory to download to in `wp-contents/plugins` or `wo-contents/themes` when given a github URL. Although the suggested fix above would work if the project name is the same as the plugin name, this isn't always the case, eg https://github.com/Miller-Media/modern-wordpress where the plugin name is `modern-framework`.

Probably a better thing to do here would be to add an optional `--dir` option (or simliar) to say what the plugin/theme directory name should be.

**Comment by schlessera** [comment]
Our package manager contains code to download the `composer.json` file from a GitHub repository and extract the package name out of it. We could use that same technique here.

**Comment by scarstens** [comment]
I think passing a flag to indicate the "package name" or "folder name" was already rejected in earlier tickets to the WP-CLI. I mean it seems like a sound solution to me, but I thought I'd mention that there must have been reasons not to move forward with that solution.

**Comment by gitlost** [comment]
Ta @scarstens , yes that seems the most sensible solution, though I haven't found any issues mentioning it apart from this recent one https://github.com/wp-cli/extension-command/issues/74 (but then I'm not very good at searching github).

Re multiple installls, there could be a number of ways of dealing with it, one of which is that it only applies to the first one!

But anyway, just to address this particular issue, I'm going to push a stopgap PR based on the original suggestion soon.
