### ISSUE TITLE
Theme Upload Time out

### ISSUE THREAD

**Issue by leocreary** [wp-cli/extension-command#93]
I need some feedback, I just downloaded a theme I've been trying to upload into wordpress and everytime I try to upload the zip. file it times out and error message, "try again later"

**Comment by danielbachhuber** [comment]
Hi @leocreary,

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. Bug reports need to be reproducible with a fresh WordPress install. If your issue only reproduces in your environment, then it's likely specific to your environment. For support options, please review http://wp-cli.org/#support
