### ISSUE TITLE
Expose the w.org URL in plugin search results

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/extension-command#94]
When using `wp plugin search`, there's no way to quickly access to the plugin's w.org page to get more information about the plugin.

An extra field for the URL would be useful.

**Comment by schlessera** [comment]
Yes, would allow users with smart terminals to click the link to access the page, and also makes sense if you want to directly retrieve the URL in a script as well.

**Comment by GaryJones** [comment]
I've got a fix ready to go on this.
