### ISSUE TITLE
Introduce wp theme mod list

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/extension-command#97]
Most commands in WP-CLI that operate on collections of data provide a `list` command. `wp theme mod` is an exception. You need to use `wp theme mod get --all`.

I think for consistency, `wp theme mod list` should be implemented, even though its functionality already exists.

**Comment by schlessera** [comment]
Yes, I agree, one would expect the `list` version to exist.

**Comment by marksabbath** [comment]
Gonna work on this one.

**Comment by schlessera** [comment]
@marksabbath I'm sorry I didn't get to respond to you earlier.
I think the approach is good enough for a first iteration and can be adapted whenever we hit issues with that approach's extensibility.

However, by now another contributor has already provided a patch for this in #100.

Sorry again for not being faster to respond, and thanks for wanting to work on this.

**Comment by schlessera** [comment]
Fixed via https://github.com/wp-cli/extension-command/pull/100
