### ISSUE TITLE
Bring template files over from `wp-cli/wp-cli`

### ISSUE THREAD

**Issue by schlessera** [wp-cli/extension-command#99]
The two Mustache template files required by this repository ( `plugin-status.mustache` & `theme-status.mustache` ) are still located in the `wp-cli/wp-cli` repository. This is an oversight from https://github.com/wp-cli/wp-cli/pull/3728.

They should be moved over to this repository and then later removed from `wp-cli/wp-cli` once a new release for this package was tagged and required in `wp-cli/wp-cli`.

- [x] Copy `plugin-status.mustache` & `theme-status.mustache` into `wp-cli/extension-command`
- [x] Add `plugin-status.mustache` & `theme-status.mustache` to inclusion list in `utils/make-phar.php`
- [x] Tag a new release of `wp-cli/extension-command` with added files
- [x] Require that release or higher of `wp-cli/extension-command` in `wp-cli/wp-cli`
- [x] Remove `plugin-status.mustache` & `theme-status.mustache` from `wp-cli/wp-cli`

**Comment by wojsmol** [comment]
@schlessera This was fixed by merging https://github.com/wp-cli/wp-cli/pull/4854.
